import {sideDistrictPoint,EXTRA_DISTRICT_PLACEMENTS} from './district-content.js?v=900';
import {AREA_BY_ID,ENEMIES} from './data.js?v=900';
import {makeItem} from './loot.js?v=900';
import {spaciousPoint} from './hub-space.js?v=900';
export const ADVENTURES={
 'adventure-metro':{name:'De Metrowerkplaats',hub:'canal',chapter:'delta',zone:0,reward:75,xp:45,weights:[12,58,28,2,0],objectives:['Pompzekering','Signaalmodule','Voedingskast'],groups:[['crawler','drone'],['sniper','minecrab'],['eel','raider','crawler']]},
 'adventure-caravan':{name:'De Verloren Karavaan',hub:'highway',chapter:'highway',zone:1,reward:115,xp:70,weights:[4,47,40,9,0],objectives:['Medicijnkrat','Focuskoffer','Accuvoorraad'],groups:[['hunter','raider'],['repairer','bulwark'],['sniper','bulwark','hunter']]},
 'adventure-bio':{name:'Het Stille Laboratorium',hub:'forest',chapter:'forest',zone:2,reward:165,xp:95,weights:[0,38,49,12,1],objectives:['Filtercultuur','Archiefkopie','Isoleermodule'],groups:[['plaguewright','beast'],['repairer','toxinbeetle'],['plaguewright','bulwark','hunter']]},
 'adventure-radar':{name:'De Hoogteradar',hub:'skybridge',chapter:'skybridge',zone:3,reward:215,xp:110,weights:[0,24,57,18,1],objectives:['Antennarelais','Koelmodule','Noodaccu'],groups:[['resonant','hunter'],['stormnest','repairer'],['siege','bulwark','hunter']]}
};
export const ADVENTURE_NPCS={canal:{id:'routes',name:'Milo · Nevenroutes',title:'Bergingsexpedities · F',x:831.25,y:256.25,art:1,routes:true},forest:{id:'routes',name:'Milo · Nevenroutes',title:'Bergingsexpedities · F',x:925,y:656.25,art:1,routes:true},skybridge:{id:'routes',name:'Milo · Nevenroutes',title:'Bergingsexpedities · F',x:1620,y:645,art:1,routes:true}};
Object.assign(ADVENTURE_NPCS.forest,{x:865,y:282.5});
for(const id of Object.keys(ADVENTURE_NPCS))ADVENTURE_NPCS[id]=spaciousPoint(ADVENTURE_NPCS[id],id);
for(const [id,npc]of Object.entries(ADVENTURE_NPCS))[npc.x,npc.y]=sideDistrictPoint(id,EXTRA_DISTRICT_PLACEMENTS[id].board);
export const AdventureRules={
 startAdventure(id){const spec=ADVENTURES[id];if(!spec||!this.inCamp()||!this.isUnlocked(id)||this.state.player.inventory.length>=48||this.challengeBuildLocked())return false;delete this.state.areas[id];return this.enterArea(id);},
 createAdventureWorld(w,area){const spec=ADVENTURES[area.id],positions=area.objectives;w.adventure={claimed:[],paid:false};w.coreCollected=true;w.sideDone=false;w.loot=[];w.hazards=[];w.relays=[];w.enemies=[];w.gate=null;
  w.objectives=positions.map(([x,y],i)=>({id:i,x,y,name:spec.objectives[i],done:false}));
  for(let i=0;i<3;i++)for(const [j,type]of spec.groups[i].entries()){const [x,y]=positions[i],e=this.makeEnemy(type,x+(j-1)*65,y-70-j*20,i===2&&j===0);e.objectiveId=i;e.noReward=true;this.placeSummon(e);w.enemies.push(e);}return w;
 },
 adventureInteraction(){const w=this.state.world;if(!w.adventure)return null;const p=this.state.player,o=w.objectives.find(o=>!o.done&&Math.hypot(o.x-p.x,(o.y-p.y)*1.15)<100);if(!o)return null;const guarded=w.enemies.some(e=>!e.dead&&e.objectiveId===o.id);return {type:guarded?'adventureGuard':'adventureObjective',entity:o,label:guarded?'Versla de bewakers van '+o.name:'Berg '+o.name+' · '+w.adventure.claimed.length+'/3',key:'F'};},
 collectAdventureObjective(id){const s=this.state,w=s.world,o=w.objectives?.find(o=>o.id===id);if(!w.adventure||!o||o.done||Math.hypot(o.x-s.player.x,(o.y-s.player.y)*1.15)>=100||w.enemies.some(e=>!e.dead&&e.objectiveId===id))return false;o.done=true;w.adventure.claimed.push(id);this.notice(o.name+' geborgen · '+w.adventure.claimed.length+'/3');this.emit('loot');return true;},
 updateAdventure(){const s=this.state,w=s.world,a=w.adventure;if(!a||a.paid||a.claimed.length!==3||w.enemies.some(e=>!e.dead)||s.mode!=='playing')return false;const spec=ADVENTURES[s.area];a.paid=true;w.sideDone=true;s.player.scrap+=spec.reward;s.player.xp+=spec.xp;s.adventureVictories||={};s.adventureVictories[s.area]=(s.adventureVictories[s.area]||0)+1;const item=makeItem({rng:this.rng,level:Math.max(2+spec.zone*3,Math.min(5+spec.zone*3,s.player.level)),profile:'cache',uid:++this.idCounter,rarity:this.adventureRarity(spec.weights)}),exit=AREA_BY_ID[s.area].exit;w.loot.push({id:++this.idCounter,x:exit[0]*1920-90,y:exit[1]*1280+50,type:'loot',item,expeditionReward:true});this.notice('Berging klaar · +'+spec.reward+' schroot · één vondst · terugpoort open','#ffe0a2');this.emit('relaydone');return true;},
 adventureRarity(weights){let value=this.rng()*100;for(let i=0;i<weights.length;i++){value-=weights[i];if(value<0)return ['common','uncommon','rare','epic','legendary'][i];}return 'rare';}
};
export function adventureBoard(g){const p=g.state.player;return `<p class="menu-intro">Drie bewaakte bergingspunten per expeditie. Verken, versla de bewakers en berg de onderdelen met F. De hoofdarena’s houden hun eigen tempo. Elke voltooiing geeft één vondst en schroot; opnieuw starten herstelt je leven of voorraad niet.</p><div class="adventure-board">${Object.entries(ADVENTURES).map(([id,s])=>{const open=g.isUnlocked(id);return `<article><img src="assets/painted/${AREA_BY_ID[id].file}" alt=""><div><small>OPTIONEEL · HERHAALBAAR · REGIO ${s.zone+1}</small><h3>${s.name}</h3><p>${AREA_BY_ID[id].story}</p><b>${s.reward} schroot + één willekeurig item</b><button data-start-adventure="${id}" ${open&&g.inCamp()&&p.inventory.length<48?'':'disabled'}>${open?'Start berging':'Na '+AREA_BY_ID[s.chapter].name}</button></div></article>`;}).join('')}</div>`;}
