import {SCENERY_CATALOG} from './scenery-catalog.js?v=910';
import {MODULE_LAYOUTS} from './scenery-modules.js?v=910';
const $=id=>document.getElementById(id),images=new Map(),used=new Set(Object.values(MODULE_LAYOUTS).flatMap(layout=>layout.pieces.map(p=>p.type)));
const words={nl:{heading:'Assetbibliotheek',intro:'Losse vloeren en decorstukken om opnieuw te gebruiken. Elke asset heeft een vaste schaal, een plaatsingspunt en een grondvlak. De groene lijn toont loopbare vloer; de amberkleurige lijn toont de basis die beweging blokkeert.',language:'Taal',search:'Zoeken',placeholder:'Bijvoorbeeld: bank, steen of tuin',category:'Soort',biome:'Omgeving',all:'Alles',floor:'Vloeren',prop:'Decorstukken',garden:'Tuin',city:'Stad',ruins:'Ruïnes',industrial:'Industrieel',footprints:'Grondvlak tonen',inUse:'In gebruik',available:'Beschikbaar voor plaatsing',walkable:'Loopbare vloer',solid:'Alleen de basis blokkeert',copy:'Kopieer plaatsing',details:'Plaatsingsgegevens',copied:'Plaatsing gekopieerd. Vul de gewenste positie in.',copyFallback:'Selecteer de plaatsingsgegevens om te kopiëren.',empty:'Geen assets gevonden.',count:(n,total,bytes)=>`${n} van ${total} assets · hele bibliotheek ${(bytes/1024).toFixed(0)} kB`,footer:'Nieuwe stukken staan klaar voor latere plaatsing. Plaatsing gebruikt dezelfde gegevens voor beeld en blokkade. Controleer bij ieder nieuw gebied de daadwerkelijke route langs de objecten.',database:'Download het assetregister',game:'Terug naar het spel',loading:'Afbeeldingen voorbereiden…',failure:'Een afbeelding kon niet worden geladen.'},en:{heading:'Asset library',intro:'Separate floors and props to reuse. Each asset has a fixed scale, an anchor and a ground footprint. The green line marks walkable floor; the amber line marks the base that blocks movement.',language:'Language',search:'Search',placeholder:'For example: bench, stone or garden',category:'Type',biome:'Environment',all:'All',floor:'Floors',prop:'Props',garden:'Garden',city:'City',ruins:'Ruins',industrial:'Industrial',footprints:'Show footprints',inUse:'In use',available:'Ready for placement',walkable:'Walkable floor',solid:'Only the base blocks movement',copy:'Copy placement',details:'Placement data',copied:'Placement copied. Enter the desired position.',copyFallback:'Select the placement data to copy it.',empty:'No assets found.',count:(n,total,bytes)=>`${n} of ${total} assets · complete library ${(bytes/1024).toFixed(0)} kB`,footer:'New pieces are ready for future placement. Drawing and collision use the same placement data. Check the actual route around objects in each new area.',database:'Download the asset register',game:'Return to the game',loading:'Preparing images…',failure:'An image could not be loaded.'}};
let language=new URL(location.href).searchParams.get('lang')==='en'?'en':'nl';$('language').value=language;
function text(){return words[language];}
function setOptions(id,keys){const select=$(id),value=select.value;select.replaceChildren(...keys.map(key=>{const o=document.createElement('option');o.value=key==='all'?'':key;o.textContent=text()[key];return o;}));if([...select.options].some(o=>o.value===value))select.value=value;}
function localize(){const t=text();document.documentElement.lang=language;document.title='Gouden Horizon · '+t.heading;for(const [id,key]of Object.entries({heading:'heading',intro:'intro','language-label':'language','search-label':'search','category-label':'category','biome-label':'biome','footprint-label':'footprints','footer-note':'footer','database-link':'database','game-link':'game'}))$(id).textContent=t[key];$('search').placeholder=t.placeholder;setOptions('category',['all','floor','prop']);setOptions('biome',['all','garden','city','ruins','industrial']);render();}
function draw(canvas,a,image){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const scale=Math.min(390/a.size[0],255/a.size[1]),w=a.size[0]*scale,h=a.size[1]*scale,x=(canvas.width-w)/2,y=(canvas.height-h)/2;ctx.drawImage(image,x,y,w,h);if(!$('footprints').checked)return;const px=x+a.anchor[0]*w,py=y+a.anchor[1]*h;ctx.lineWidth=2.5;ctx.strokeStyle=a.category==='floor'?'#a9efb8':'#ffd37a';ctx.fillStyle=a.category==='floor'?'#a9efb814':'#ffd37a22';ctx.beginPath();if(a.category==='floor'){ctx.moveTo(px-w/2,py);ctx.lineTo(px,py-h/2);ctx.lineTo(px+w/2,py);ctx.lineTo(px,py+h/2);ctx.closePath();}else ctx.ellipse(px,py,a.footprint.rx*w,a.footprint.ry*w,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(px,py,3,0,Math.PI*2);ctx.fill();}
function render(){const t=text(),query=$('search').value.trim().toLocaleLowerCase(),category=$('category').value,biome=$('biome').value,assets=SCENERY_CATALOG.assets.filter(a=>(!category||a.category===category)&&(!biome||a.biomes.includes(biome))&&(!query||[a.id,...Object.values(a.label),...a.tags].join(' ').toLocaleLowerCase().includes(query)));$('summary').textContent=t.count(assets.length,SCENERY_CATALOG.assets.length,SCENERY_CATALOG.assets.reduce((n,a)=>n+a.bytes,0));$('assets').replaceChildren();if(!assets.length){const p=document.createElement('p');p.className='empty';p.textContent=t.empty;$('assets').append(p);return;}for(const a of assets){const card=document.createElement('article');card.className='card';card.dataset.asset=a.id;const canvas=document.createElement('canvas');canvas.width=460;canvas.height=310;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',a.label[language]);if(images.has(a.id))draw(canvas,a,images.get(a.id));const body=document.createElement('div');body.className='body';const heading=document.createElement('h2');heading.textContent=a.label[language];const badge=document.createElement('span');badge.className='badge';badge.textContent=used.has(a.id)?t.inUse:t.available;const meta=document.createElement('p');meta.className='meta';meta.textContent=`${a.size.join(' × ')} px · ${(a.bytes/1024).toFixed(1)} kB · ${a.biomes.map(b=>t[b]).join(', ')}\n${a.category==='floor'?t.walkable:t.solid}`;const placement={id:'unique-instance-name',type:a.id,point:['x','y'],...a.defaultPlacement};const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent=t.details;pre.textContent=JSON.stringify(placement,null,2);details.append(summary,pre);const button=document.createElement('button');button.textContent=t.copy;button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(pre.textContent);$('status').textContent=t.copied;}catch{details.open=true;$('status').textContent=t.copyFallback;}});body.append(heading,badge,meta,button,details);card.append(canvas,body);$('assets').append(card);}}
for(const id of ['search','category','biome','footprints'])$(id).addEventListener(id==='search'?'input':'change',render);
$('language').addEventListener('change',()=>{language=$('language').value;const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);$('status').textContent='';localize();});
localize();$('status').textContent=text().loading;
try{await Promise.all(SCENERY_CATALOG.assets.map(a=>new Promise((resolve,reject)=>{const image=new Image();image.onload=async()=>{try{await image.decode();images.set(a.id,image);resolve();}catch(e){reject(e);}};image.onerror=reject;image.src=a.file;})));$('status').textContent='';render();}catch{$('status').textContent=text().failure;render();}
