// Authoritative two-player simulation. Rendering and menus remain browser-side.
import {Engine,copy,distance,canStand,seeded} from './engine.js?v=905';
import {EnemyCrowd} from './enemy-ai.js?v=905';
import {updateEnemyMotion} from './enemy-motion.js?v=905';
import {AREA_BY_ID,ENEMIES} from './data.js?v=905';
import {START_BUILDS} from './specializations.js?v=905';
const PERSONAL=['player','mode','pending','notices','summons','ultimateWave'];
export const COOP_HP=1.7,COOP_DAMAGE=1.08;
export const RPC_METHODS=new Set(['unlockTestMode','lockTestMode','testTravel','interact','castSlot','castRight','dash','heal','useAntidote','ultimate','commandCompanions','closeModal','chooseUpgrade','purchaseUpgrade','chooseLoot','equipItem','recycleItem','sellItem','sellItems','buyItem','buySupply','buyAntidote','reinforce','buySpell','setMainAttack','selectSpell','assignRight','assignSkill','clearSkillSlot','setItemMark','learnSpellVariant','selectSpellVariant','selectCompanion','upgradeCompanion','chooseSpecialization','chooseTalent','resetSpecialization','gambleLoot','buyUniqueRecipe','acceptQuest','claimQuest','acceptCityQuest','claimCityQuest','acceptQuarterQuest','claimQuarterQuest','inspectQuarterPoint','craftRune','startAdventure','startBounty','startChallenge','restartChallenge','enterArea','setDestination','openQuayGarden','switchAreaSection','acceptSalvageQuest','claimSalvageReward','deferUpgrade','recycleLoot','selectDestination','returnFromChallenge','weaveRune','craftAtelierItem']);
export function heroIdentity(p,name,build){p.name=String(name||'Reiziger').replace(/[^\p{L}\p{N} _.-]/gu,'').trim().slice(0,18)||'Reiziger';p.characterClass=build;p.preferredSpecialization=build;const look={elementalist:['storm','storm'],builder:['filter','crystal'],hunter:['light','tidal']}[build]||['light','tidal'];p.equipment.suit.appearance=look[0];p.equipment.weapon.appearance=look[1];return p;}
export function cleanInput(input={}){const finite=(n,min,max)=>Number.isFinite(n)?Math.max(min,Math.min(max,n)):0;return {x:finite(input.x,-1,1),y:finite(input.y,-1,1),shoot:input.shoot===true,right:input.right===true,paused:input.paused===true,aim:input.aim&&Number.isFinite(input.aim.x)&&Number.isFinite(input.aim.y)?{x:finite(input.aim.x,0,6000),y:finite(input.aim.y,0,2500)}:null,slots:[...new Set((Array.isArray(input.slots)?input.slots:[]).slice(0,6).filter(n=>Number.isInteger(n)&&n>=0&&n<6))]};}
export class CoopSession {
 constructor(seed=Date.now()%1000000){this.seed=seed;this.actors=[];this.started=false;this.time=0;this.rotation=0;this.travel=null;this.checkpoint=null;}
 join({token,name,build='elementalist',gender='male'}={}){let actor=token&&this.actors.find(a=>a.token===token);if(actor){actor.connected=true;actor.input={};return actor;}if(this.started||this.actors.length>=2)throw Error('Deze expeditie heeft al twee spelers. Gebruik je eigen tab om opnieuw te verbinden.');if(!START_BUILDS.some(b=>b.id===build))build='elementalist';actor={id:['hero-1','hero-2'].find(id=>!this.actors.some(a=>a.id===id)),token,name,build,gender:gender==='female'?'female':'male',ready:false,connected:true,input:{},inputAt:0,events:[],threatHits:{},summons:[],notices:[],mode:'playing',pending:null,ultimateWave:null};actor.name=String(name||'Reiziger').replace(/[^\p{L}\p{N} _.-]/gu,'').trim().slice(0,18)||'Reiziger';if(this.actors.some(a=>a.name===actor.name))actor.name=actor.name.slice(0,16)+' 2';this.actors.push(actor);return actor;}
 leave(id){const a=this.actor(id);if(a){a.connected=false;a.input={};}if(!this.started)this.actors=this.actors.filter(a=>a.id!==id);}
 actor(id){return this.actors.find(a=>a.id===id);}
 ready(id){const a=this.actor(id);if(a)a.ready=true;if(this.actors.length===2&&this.actors.every(a=>a.ready&&a.connected))this.start();}
 start(){this.engine=new Engine(START_BUILDS.find(b=>b.id===this.actors[0].build).discipline,this.seed);const g=this.engine;
  for(const [i,a] of this.actors.entries()){const base=i===0?g:new Engine(START_BUILDS.find(b=>b.id===a.build).discipline,this.seed+i);a.player=heroIdentity(copy(base.state.player),a.name,a.build);a.player.heroId=a.id;a.player.heroGender=a.gender||'male';a.player.y+=i*55;for(const item of [...Object.values(a.player.equipment),...a.player.inventory])item.uid=++g.idCounter;}
  this.started=true;this.encounterLevel=1;this.engine.state.world.partyPrepared=true;this.install();this.distributeCaches(g.state.world);this.partyCheckpoint();
 }
 withActor(a,fn,physics=false){const g=this.engine,s=g.state,previous={};for(const k of PERSONAL){previous[k]=s[k];s[k]=a[k];}const active=this.active;this.active=a;const beforeMode=a.mode;if(physics&&a.player.hp>0)s.mode='playing';const ids=new Set(s.projectiles.map(b=>b.id)),fields=new Set(s.fields.map(b=>b.id)),hazards=new Set(s.world.hazards.map(b=>b.id));let result;
  try{result=fn();}finally{for(const b of s.projectiles)if(b.team==='player'&&!ids.has(b.id))b.ownerId=a.id;for(const f of s.fields)if(!fields.has(f.id))f.ownerId=a.id;for(const h of s.world.hazards)if(h.type==='friendlyFire'&&!hazards.has(h.id))h.ownerId=a.id;
   for(const k of PERSONAL)a[k]=s[k];if(physics&&s.mode==='playing'&&beforeMode!=='playing')a.mode=beforeMode;if(s.mode==='won'&&beforeMode!=='won')for(const other of this.actors){other.mode='won';other.pending=null;}if(a.player.hp<=0){a.player.hp=0;a.player.downed=true;a.mode='downed';a.pending=null;}for(const k of PERSONAL)s[k]=previous[k];this.active=active;}
  return result;
 }
 install(){const g=this.engine,originalEnter=g.enterArea.bind(g),originalMake=g.makeEnemy.bind(g),originalKill=g.killEnemy.bind(g),originalEmit=g.emit.bind(g),originalInteraction=g.interaction.bind(g);this.originalEnter=originalEnter;this.originalSwitchSection=g.switchAreaSection.bind(g);g.switchAreaSection=index=>this.requestSection(this.active||this.actors[0],index);
  g.checkpoint=()=>{};g.serialize=()=>null;
  g.emit=(type,data={})=>{const event={type,...data};if(this.active&&!['enemyattack','relay','relaydone','guardian','win','clearspore'].includes(type))this.active.events.push(event);else for(const a of this.actors)a.events.push(event);};
  g.makeEnemy=(...args)=>{const level=g.state.player.level;g.state.player.level=this.encounterLevel||Math.max(...this.actors.map(a=>a.player.level));let e;try{e=originalMake(...args);}finally{g.state.player.level=level;}e.hp=e.maxHp=Math.round(e.maxHp*COOP_HP);e.damageMultiplier=(e.damageMultiplier||1)*COOP_DAMAGE;e.partyDamage=COOP_DAMAGE;e.partySize=2;return e;};
  g.killEnemy=e=>{if(e.dead)return;const owner=this.active||this.actors[0],xp=owner.player.xp,scrap=owner.player.scrap,loot=new Set(g.state.world.loot.map(l=>l.id));originalKill(e);
   if(!e.noReward)for(const a of this.actors)if(a!==owner){a.player.xp+=owner.player.xp-xp;a.player.scrap+=owner.player.scrap-scrap;}
   for(const l of g.state.world.loot)if(!loot.has(l.id))l.ownerId=this.actors[this.rotation++%2].id;
   if(ENEMIES[e.type].boss&&!e.noReward){const drop=g.state.world.loot.find(l=>!loot.has(l.id)&&l.item);if(drop){drop.ownerId=owner.id;const other=this.actors.find(a=>a!==owner),extra=copy(drop);extra.id=++g.idCounter;extra.item.uid=++g.idCounter;extra.ownerId=other.id;extra.x+=45;g.state.world.loot.push(extra);}}
  };
  // Only the owner can select or collect a personal drop; health and scrap stay shared ground objects.
  g.interaction=()=>{const w=g.state.world,all=w.loot;w.loot=all.filter(l=>!l.ownerId||l.ownerId===this.active?.id);try{return originalInteraction();}finally{w.loot=all;}};
  g.forEachLivingHero=fn=>{for(const a of this.actors)if(a.player.hp>0)this.withActor(a,()=>fn(a.player),true);};
  g.enterArea=(id,from)=>this.requestTravel(this.active,id,from);
  g.hurtPartyArea=(point,r,damage,type)=>{for(const a of this.actors)if(a.player.hp>0)this.withActor(a,()=>{g.hurtCompanions(point,r,damage);if(distance(a.player,point)<r)g.hurtPlayer(damage,type);},true);};
  for(const name of ['spawnRelayWave','spawnExpeditionWave','spawnChallengeWave','spawnV8Wave','spawnBiomeWave','spawnNatureWave','spawnOutdoorEncounter'])if(typeof g[name]==='function'){const original=g[name].bind(g);g[name]=(...args)=>{const w=args[0]?.enemies?args[0]:g.state.world,before=new Set(w.enemies.map(e=>e.id));const result=original(...args);this.addDensity(w,w.enemies.filter(e=>!before.has(e.id)));return result;};}
 }
 addDensity(w,newEnemies){if(w.safeHub&&!newEnemies.some(e=>e.outdoor))return;const candidates=newEnemies.filter(e=>!ENEMIES[e.type].boss&&!e.elite&&!e.noReward&&!e.partyExtra);const count=Math.floor(candidates.length*.3);for(let i=0;i<count;i++){const source=candidates[Math.floor(i*candidates.length/count)],e=this.engine.placeSummon(this.engine.makeEnemy(source.type,source.x+60,source.y+35,false,source.awake));for(const key of ['relayId','objectiveId','wave','trialWave','outdoor'])if(source[key]!==undefined)e[key]=source[key];if(source.outdoor){e.hp=e.maxHp=source.maxHp;e.damageMultiplier=source.damageMultiplier;e.cooldownMultiplier=source.cooldownMultiplier;e.speedMultiplier=source.speedMultiplier;e.level=source.level;e.chapterBalanceVersion=source.chapterBalanceVersion;if(this.engine.inCamp(e)){e.x=source.x;e.y=source.y;e.home={x:e.x,y:e.y};}}e.partyExtra=true;w.enemies.push(e);}}
 distributeCaches(w){for(const l of [...w.loot])if(!l.ownerId&&!l.quest){l.ownerId=this.actors[0].id;const clone=copy(l);clone.id=++this.engine.idCounter;if(clone.item)clone.item.uid=++this.engine.idCounter;clone.x+=42;clone.ownerId=this.actors[1].id;w.loot.push(clone);}}
 requestSection(a,index){const route=this.engine.sectionTransition(index);if(!a||!route||route.locked)return false;if(this.travel?.kind==='section'&&this.travel.id===this.engine.state.area&&this.travel.section===index)this.travel.accepted.add(a.id);else this.travel={kind:'section',id:this.engine.state.area,section:index,name:route.name,accepted:new Set([a.id]),expires:this.time+20};return this.travel.accepted.size===2?this.commitTravel():true;}
 requestTravel(a,id,from){if(!a||!AREA_BY_ID[id]||!this.engine.isUnlocked(id))return false;if(this.travel?.kind!=='section'&&this.travel?.id===id){this.travel.accepted.add(a.id);}else this.travel={id,from:from||this.engine.state.area,accepted:new Set([a.id]),expires:this.time+20};if(this.travel.accepted.size===2)return this.commitTravel();return true;}
 acceptTravel(id){const a=this.actor(id);if(this.travel&&a){this.travel.accepted.add(id);if(this.travel.accepted.size===2)this.commitTravel();}}
 commitTravel(){if(this.engine.testModeEnabled())for(const a of this.actors)this.withActor(a,()=>{a.player.hp=this.engine.stats().maxHp;a.player.downed=false;},true);if(this.actors.some(a=>a.player.hp<=0))return false;const travel=this.travel;this.travel=null;this.encounterLevel=Math.max(...this.actors.map(a=>a.player.level));const host=this.actors[0],g=this.engine;let entered=false;this.withActor(host,()=>{entered=travel.kind==='section'?this.originalSwitchSection(travel.section):this.originalEnter(travel.id,travel.from);});if(!entered)return false;if(g.testModeEnabled()&&travel.id==='canal')g.state.world.gardenOpen=true;
  for(const [i,a]of this.actors.entries()){if(i){let found=false;for(const [dx,dy]of [[50,40],[-50,40],[0,65],[65,0],[-65,0]])if(canStand(host.player.x+dx,host.player.y+dy,18,g.state.area)){a.player.x=host.player.x+dx;a.player.y=host.player.y+dy;found=true;break;}if(!found){a.player.x=host.player.x;a.player.y=host.player.y;}}a.mode='playing';a.pending=null;a.summons=[];a.ultimateWave=null;a.input={};if(AREA_BY_ID[g.state.area].endgame)this.withActor(a,()=>{Object.assign(a.player,{hp:g.stats().maxHp,mana:g.stats().maxMana,spellCd:{},ultimate:0,ultimateCooldown:0,healCooldown:0,antidoteCooldown:0,venom:0,venomDamage:0,venomTick:0,venomGuard:0,wet:0,poison:0,heat:0,dashCharges:2,dashRecharge:0,ward:0,wardTime:0,rootSlow:0,echoCount:0,effectCooldowns:{}});});a.player.velocity={x:0,y:0};a.player.trail=[];a.player.invincible=1.2;a.events.push({type:travel.kind==='section'?'section':'zone',zone:g.state.zone,area:g.state.area});}
  if(!g.state.world.partyPrepared){g.state.world.partyPrepared=true;this.addDensity(g.state.world,g.state.world.enemies);this.distributeCaches(g.state.world);}
  this.partyCheckpoint();return true;
 }
 partyCheckpoint(){const g=this.engine;if(!g)return;this.checkpoint={state:copy({...g.state,checkpoint:null,areas:{...g.state.areas,[g.state.area]:g.state.world}}),actors:copy(this.actors.map(a=>({id:a.id,player:a.player}))),rng:g.rng.getState(),counter:g.idCounter};}
 retry(){if(!this.checkpoint||!this.actors.every(a=>a.player.hp<=0))return false;const cp=copy(this.checkpoint);this.engine.state=cp.state;this.engine.state.world=this.engine.state.areas[this.engine.state.area];this.engine.idCounter=cp.counter;this.engine.rng=seeded(cp.rng);for(const a of this.actors){a.player=cp.actors.find(p=>p.id===a.id).player;a.mode='playing';a.pending=null;a.summons=[];a.ultimateWave=null;a.events=[];a.threatHits={};a.input={};}return true;}
 respawnAtHub(){
  if(!this.actors.every(a=>a.player.hp<=0))return false;
  const g=this.engine,hub=this.withActor(this.actors[0],()=>g.respawnHub()),from=g.state.area;if(!hub||!this.retry())return false;
  for(const a of this.actors)this.withActor(a,()=>{Object.assign(a.player,{hp:g.stats().maxHp,mana:g.stats().maxMana,venom:0,venomTick:0,venomDamage:0,poison:0,heat:0,wet:0,rootSlow:0});});
  g.state.destination=null;this.travel={id:hub,from,accepted:new Set(this.actors.map(a=>a.id)),expires:this.time+20};return this.commitTravel();
 }
 input(id,data){const a=this.actor(id);if(a){a.input=cleanInput(data);a.inputAt=this.time;}}
 rpc(id,method,args=[]){const a=this.actor(id);if(!a||!this.started||!a.connected||!this.actors.every(p=>p.connected))return false;if(method==='acceptTravel'){this.acceptTravel(id);return true;}if(method==='retry')return this.retry();if(method==='respawnAtHub')return this.respawnAtHub();if(!RPC_METHODS.has(method)||typeof this.engine[method]!=='function'||!Array.isArray(args)||args.length>4||JSON.stringify(args).length>2000||a.player.hp<=0&&!['unlockTestMode','lockTestMode','testTravel'].includes(method))return false;
  if(method==='restartChallenge'){const trial=this.engine.state.world.trial;if(!trial)return false;this.engine.state.challengeRequest={id:trial.id,tier:trial.tier};return this.requestTravel(a,trial.id,this.engine.state.area);}
  if(method==='interact'){const fallen=this.actors.find(p=>p!==a&&p.player.hp<=0&&distance(p.player,a.player)<95);if(fallen){if(!a.player.potions||a.player.healCooldown>0)return false;a.revive={target:fallen.id,time:0,position:{x:a.player.x,y:a.player.y},hurt:a.player.lastHurt};return true;}}
  return this.withActor(a,()=>{const xp=a.player.xp,scrap=a.player.scrap,before=a.player.inventory.length,result=this.engine[method](...args);if(result&&['claimCityQuest','claimQuarterQuest','claimSalvageReward'].includes(method))for(const other of this.actors)if(other!==a){other.player.xp+=Math.max(0,a.player.xp-xp);other.player.scrap+=Math.max(0,a.player.scrap-scrap);for(const key of ['runeWorkshopUnlocked','uniqueBlueprints','contractUnlocked'])if(a.player[key])other.player[key]=a.player[key];for(const item of a.player.inventory.slice(before)){const clone=copy(item);clone.uid=++this.engine.idCounter;if(other.player.inventory.length<48)other.player.inventory.push(clone);else this.engine.state.world.loot.push({id:++this.engine.idCounter,x:other.player.x,y:other.player.y,type:'loot',item:clone,ownerId:other.id});}}return result;});
 }
 // Threat clones share one age progression, but each hero gets its own collision state.
 threats(dt){const g=this.engine,w=g.state.world,base=copy(w.threats),terrain=w.bossTerrain?copy(w.bossTerrain):null,hazards=copy(w.hazards);let hostThreats,hostTerrain,hostHazards;const removed=new Set();
  for(const [i,a]of this.actors.entries())if(a.player.hp>0){w.threats=copy(base);for(const t of w.threats)t.hit=Boolean(a.threatHits[t.id]);if(terrain)w.bossTerrain=copy(terrain);w.hazards=copy(hazards);if(hostThreats)for(const h of w.hazards)if(h.type==='friendlyFire')h.cleared=true;
   this.withActor(a,()=>{g.updateThreats(dt);g.updateHazards(dt);},true);for(const t of w.threats)if(t.hit)a.threatHits[t.id]=true;for(const t of base)if(!w.threats.some(v=>v.id===t.id))removed.add(t.id);
   if(!hostThreats){hostThreats=w.threats;hostTerrain=w.bossTerrain;hostHazards=w.hazards;}
  }
  w.threats=(hostThreats||base).filter(t=>!removed.has(t.id));if(hostTerrain)w.bossTerrain=hostTerrain;w.hazards=hostHazards||hazards;
 }
 tick(dt){if(!this.started||!this.actors.every(a=>a.connected)||this.actors.every(a=>a.player.hp<=0))return;const g=this.engine,s=g.state,host=this.actors.find(a=>a.player.hp>0);this.time+=dt;let countdown=false;this.withActor(host,()=>{countdown=g.updateChallengeCountdown(dt);},true);if(countdown)return;s.time+=dt;s.runTime+=dt;if(this.travel&&this.travel.expires<this.time)this.travel=null;
  for(const a of this.actors){if(a.player.hp<=0)continue;const input=this.time-a.inputAt<.3&&!a.input.paused&&a.mode==='playing'?a.input:{};this.withActor(a,()=>{g.updateActor(dt,input);g.updateCompanions(dt);},true);
   if(a.revive){const target=this.actor(a.revive.target);if(!target||target.player.hp>0||distance(a.player,a.revive.position)>12||distance(a.player,target.player)>95||a.player.lastHurt!==a.revive.hurt||input.x||input.y||a.player.hp<=0)a.revive=null;else {a.revive.time+=dt;if(a.revive.time>=2){a.player.potions--;a.player.healCooldown=10;this.withActor(target,()=>{target.player.hp=g.stats().maxHp*.25;},true);target.player.downed=false;target.player.venom=0;target.player.poison=0;target.player.invincible=1.5;target.mode='playing';target.pending=null;a.revive=null;target.events.push({type:'heal'});}}}
  }
  this.threats(dt);
  const crowd=new EnemyCrowd(s.world.enemies);for(const e of [...s.world.enemies]){const alive=this.actors.filter(a=>a.player.hp>0),outside=alive.filter(a=>!g.inCamp(a.player)),living=outside.length?outside:alive;if(!living.length)break;const locked=this.actor(e.targetHero),nearest=living.reduce((a,b)=>distance(a.player,e)<distance(b.player,e)?a:b),target=locked?.player.hp>0&&(e.windup||e.leap||e.rush||e.leaping||e.rushTimer>0)?locked:nearest;e.targetHero=target.id;const old={x:e.x,y:e.y};this.withActor(target,()=>g.updateEnemies(dt,[e],crowd),true);updateEnemyMotion(e,e.x-old.x,e.y-old.y,dt);}
  // A projectile advances once. Choose a hero along its next segment for enemy bolts.
  const all=s.projectiles;s.projectiles=[];const survivors=[];for(const b of all){let a=this.actor(b.ownerId)||host;if(b.team==='enemy'){const living=this.actors.filter(a=>a.player.hp>0);a=living.sort((a,c)=>Math.min(bodyDistance(b,dt,a.player),...a.summons.filter(u=>u.hp>0&&u.life>0).map(u=>bodyDistance(b,dt,u)))-Math.min(bodyDistance(b,dt,c.player),...c.summons.filter(u=>u.hp>0&&u.life>0).map(u=>bodyDistance(b,dt,u))))[0]||host;}s.projectiles=[b];this.withActor(a,()=>g.updateProjectiles(dt),true);survivors.push(...s.projectiles);}s.projectiles=survivors;
  const fields=s.fields,remaining=[];for(const a of this.actors){s.fields=fields.filter(f=>(f.ownerId||host.id)===a.id);this.withActor(a,()=>g.updateFields(dt),true);remaining.push(...s.fields);}s.fields=remaining;
  for(const a of this.actors)if(a.player.hp>0)this.withActor(a,()=>{const scrap=a.player.scrap;g.updatePickups(dt);const earned=a.player.scrap-scrap;if(earned)for(const other of this.actors)if(other!==a)other.player.scrap+=earned;},true);
  this.withActor(host,()=>{const xp=host.player.xp,coins=host.player.scrap,inventoryBefore=host.player.inventory.length,loot=new Set(s.world.loot.map(l=>l.id));g.updateWorldProgress(dt);for(const a of this.actors)if(a!==host){for(const item of host.player.inventory.slice(inventoryBefore)){const clone=copy(item);clone.uid=++g.idCounter;if(a.player.inventory.length<48)a.player.inventory.push(clone);else s.world.loot.push({id:++g.idCounter,x:a.player.x,y:a.player.y,type:'loot',item:clone,ownerId:a.id});}if(s.pending?.type==='trialResult'){a.pending=copy(s.pending);a.mode='modal';}a.player.xp+=Math.max(0,host.player.xp-xp);a.player.scrap+=Math.max(0,host.player.scrap-coins);}for(const l of [...s.world.loot])if(!loot.has(l.id)&&!l.ownerId&&!l.quest){l.ownerId=host.id;const other=this.actors.find(a=>a!==host),clone=copy(l);clone.id=++g.idCounter;if(clone.item)clone.item.uid=++g.idCounter;clone.ownerId=other.id;clone.x+=42;s.world.loot.push(clone);}},true);
  for(const a of this.actors)if(a.player.hp>0)this.withActor(a,()=>g.updateLevel());const tankWaves=copy(s.effects.filter(e=>e.type==='tank-wave'));this.withActor(host,()=>g.updateVisuals(dt),true);for(const a of this.actors)if(a!==host&&a.player.hp>0)this.withActor(a,()=>{for(const e of tankWaves){const key='wave-'+(e.id||e.x+':'+e.y+':'+(s.time-e.age).toFixed(2));if(!a.threatHits[key]&&Math.abs(distance(a.player,e)-(40+Math.min(1,(e.age+dt)/.9)*240))<26){a.threatHits[key]=true;g.hurtPlayer(e.damage);}}},true);for(const a of this.actors)if(a!==host)a.notices=a.notices.map(n=>({...n,life:n.life-dt})).filter(n=>n.life>0);
  this.hitCleanup=(this.hitCleanup||0)+dt;if(this.hitCleanup>=1){this.hitCleanup=0;const alive=new Set([...s.world.threats.map(t=>String(t.id)),...s.effects.filter(e=>e.type==='tank-wave').map(e=>'wave-'+(e.id||e.x+':'+e.y+':'+(s.time-e.age).toFixed(2)))]);for(const a of this.actors)for(const key of Object.keys(a.threatHits))if(!alive.has(key))delete a.threatHits[key];}
 }
 exportSave(){if(!this.started||this.engine.testModeEnabled())return null;return copy({version:1,seed:this.seed,time:this.time,rotation:this.rotation,encounterLevel:this.encounterLevel,checkpoint:this.checkpoint,state:{...this.engine.state,checkpoint:null,areas:{...this.engine.state.areas,[this.engine.state.area]:this.engine.state.world}},actors:this.actors,rng:this.engine.rng.getState(),counter:this.engine.idCounter});}
 restoreSave(data){if(data?.version!==1||data.actors?.length!==2||!data.state?.world)throw Error('Invalid LAN save');this.seed=data.seed;this.time=data.time;this.rotation=data.rotation||0;this.encounterLevel=data.encounterLevel||1;this.checkpoint=data.checkpoint;this.actors=data.actors.map(a=>({...a,connected:false,input:{},events:[],revive:null}));this.engine=new Engine('tide',this.seed);this.engine.state=data.state;this.engine.state.world=this.engine.state.areas[this.engine.state.area]||data.state.world;this.engine.idCounter=data.counter;this.engine.rng=seeded(data.rng);this.started=true;this.install();}
 snapshot(id){const a=this.actor(id);if(!this.started)return {lobby:this.actors.map(p=>({id:p.id,name:p.name,build:p.build,ready:p.ready,connected:p.connected}))};const g=this.engine,s=g.state;const state={...s,testMode:g.testModeEnabled(),checkpoint:null,areas:Object.fromEntries(Object.entries(s.areas).map(([id,w])=>[id,{sideDone:w.sideDone,coreCollected:w.coreCollected,bossDefeated:w.bossDefeated,relays:w.relays,adventure:w.adventure}])),...Object.fromEntries(PERSONAL.map(k=>[k,a[k]])),world:{...s.world,loot:s.world.loot.filter(l=>!l.ownerId||l.ownerId===id)}};
  state.coop={self:id,paused:!this.actors.every(a=>a.connected),defeated:this.actors.every(a=>a.player.hp<=0),travel:this.travel?{id:this.travel.id,name:this.travel.name||AREA_BY_ID[this.travel.id].name,accepted:[...this.travel.accepted]}:null,players:this.actors.map(a=>({id:a.id,name:a.player.name,build:a.build,hp:a.player.hp,maxHp:this.withActor(a,()=>g.stats().maxHp),connected:a.connected,revive:a.revive?.time||0,player:a.id===id?null:a.player,summons:a.id===id?[]:a.summons,ultimateWave:a.id===id?null:a.ultimateWave}))};
  if(state.coop.defeated){state.mode='dead';state.pending=null;}const events=a.events.splice(0,80);return {state,events};
 }
}
function bodyDistance(b,dt,p){return segmentDistance(b,dt,{x:p.x,y:p.y-20});}
function segmentDistance(b,dt,p){const dx=(b.vx||0)*dt,dy=(b.vy||0)*dt,t=Math.max(0,Math.min(1,((p.x-b.x)*dx+(p.y-b.y)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p.x-b.x-t*dx,p.y-b.y-t*dy);}
