import {SLOT_NAMES,RARITIES} from './data.js?v=900';
import {RESISTANCES,resistance} from './resistances.js?v=900';
import {markActions} from './item-marks.js?v=900';
import {EQUIPMENT_SLOT_NAMES,itemFitsSlot,comparisonSlot} from './equipment-slots.js?v=900';
import {gearFeedback} from './gear-feedback.js?v=900';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=i=>`<img class="painted-item" src="assets/items/${i.art||i.id}.webp" alt="" draggable="false">`;
export function equipmentBody(p,stats,selected,slot,sort='rarity'){
 const bag=p.inventory.filter(i=>!slot||i.slot===slot).sort((a,b)=>sort==='level'?b.level-a.level:sort==='slot'?a.slot.localeCompare(b.slot)||RARITIES[b.rarity].rank-RARITIES[a.rarity].rank:RARITIES[b.rarity].rank-RARITIES[a.rarity].rank||b.level-a.level);
 const slots=Object.entries(p.equipment).map(([key,item])=>`<button data-gear-slot="${key}" data-rarity="${item.rarity}" class="doll-slot doll-${key} ${item.empty?'empty-slot':''} ${(key==='relic2'?'relic':key)===slot?'selected':''} ${itemFitsSlot(selected,key)?'can-place':''}" title="${itemFitsSlot(selected,key)?'Plaats '+selected.name+' in dit slot':EQUIPMENT_SLOT_NAMES[key]+': '+item.name}"><span>${art(item)}</span><small>${EQUIPMENT_SLOT_NAMES[key]}</small><strong>${item.empty?(key==='head'?'Plaats hoofdgear':'Plaats relikwie'):esc(item.name)}${item.enhance?' +'+item.enhance:''}</strong><em>${itemFitsSlot(selected,key)?'KLIK OM TE PLAATSEN':item.empty?'LEEG':RARITIES[item.rarity].name}</em></button>`).join('');
 return `<div class="equipment-workspace"><aside class="equipment-character"><div class="paper-doll"><div class="doll-hero"><canvas id="equipment-portrait" width="320" height="420" role="img" aria-label="Jouw held met zijn uitgeruste mantel, focus en hoofdgear"></canvas><span>NIVEAU ${p.level}</span></div>${slots}</div><details class="doll-stat-panel"><summary>Veldstats · ${Math.round(stats.maxHp)} leven · ${Math.round(stats.maxMana)} mana</summary><div class="doll-stats"><span>LEVEN<b>${Math.round(stats.maxHp)}</b></span><span>MANA<b>${Math.round(stats.maxMana)}</b></span><span>MANA / SEC<b>${stats.manaRegen.toFixed(1)}</b></span><span>SNELHEID<b>${Math.round(stats.moveSpeed)}</b></span><span>SPREUKBONUS<b>+${Math.round(stats.power*100)}%</b></span><span>BESCHERMING<b>${Math.round(Math.min(.55,stats.armor)*100)}%</b></span>${Object.entries(RESISTANCES).map(([key,r])=>`<span>${r.name.toUpperCase()}<b>${Math.round(resistance(stats,key)*100)}%</b></span>`).join('')}</div></details></aside><section class="equipment-bag"><div class="inventory-heading"><h3>Rugzak <small>${p.inventory.length} / 48</small></h3><label>Sorteer<select data-bag-sort="true">${[['rarity','Zeldzaamheid'],['level','Niveau'],['slot','Type']].map(([id,label])=>`<option value="${id}" ${sort===id?'selected':''}>${label}</option>`).join('')}</select></label></div><div class="bag-filters">${[['all','Alles'],...Object.entries(SLOT_NAMES)].map(([id,label])=>`<button data-bag-filter="${id}" class="${(slot||'all')===id?'selected':''}">${label}</button>`).join('')}</div><p class="bag-instruction">Klik een item voor alle details. Kies daar Uitrusten, of Vergelijken & plaatsen. Je kunt ook slepen naar een uitrustingsslot. Relikwieën passen in I én II. ★ Bewaren beschermt tegen verkoop.</p><div class="bag-grid">${bag.map(i=>{const f=gearFeedback(i,p.equipment[comparisonSlot(p,i)],p.level);return `<div class="bag-card"><button data-item="${i.uid}" data-rarity="${i.rarity}" draggable="true" class="bag-item ${selected?.uid===i.uid?'selected':''}" title="${esc(f.summary)}"><span>${art(i)}</span><strong>${esc(i.name)}</strong><small>${SLOT_NAMES[i.slot]} · ${RARITIES[i.rarity].name} · NIV. ${i.level}</small><em>${f.requiredLevel?'VANAF NIV. '+f.requiredLevel:f.summary}</em></button>${markActions(i)}</div>`;}).join('')||'<p class="empty-bag">Geen items in deze selectie.</p>'}</div></section></div>`;
}
