import {AREA_BY_ID} from './data.js?v=901';
import {STORY_ORDER} from './story.js?v=901';
import {NEXT_ROOMS} from './world-interiors.js?v=901';

// Each scene connects an existing encounter to the journey; it never invents a new quest.
export const JOURNEY_SCENES={
 canal:['Het eerste licht','Tussen de boten hangt een lantaarn die zonder olie brandt. Milo zegt dat ze antwoordt op de oude getijdenpomp. Als die weer vrij is, kan jouw meetlens de eerste lichtbrug terugvinden.','Bevrijd de pomp in de Rietdelta. Daarmee begint de zoektocht naar de drie sleutels van Aurelia.'],
 delta:['Een hart onder het riet','Onder de vlonders hoor je een trage slag. De pomp leeft nog, maar haar bewakers laten niemand bij de stroom. Je staf licht op bij iedere slag: dit is de eerste draad van het gebroken netwerk.','Zonder de getijdenpomp kunnen de meetstations in de Verdronken Ring de storm niet lezen.'],
 ring:['De storm heeft een geheugen','De twee meetstations steken als sterrenwijzers boven het water uit. In hun lenzen zit nog een laatste meting van vóór de Wereldbreuk. Breng beide wijzers op één lijn; tussen hun licht verschijnt de verloren Atmosferische lens.','De Atmosferische lens vertelt Aurelia waar zon en storm uit balans zijn. Zonder haar stuur je de magie blind.'],
 rooftops:['De kaart die bleef groeien','Een glazen kaartkoker ligt tussen de wortels van de daktuinen. De tuinwachters tekenden een droge route toen de straten beneden verdwenen. Hun laatste bewaker staat nog altijd op wacht.','De routekaart leidt je naar Vrijhaven, waar de volgende lichtbrug naar het zonnenet begint.'],
 highway:['De stad van tweede kansen','Vrijhaven klinkt naar hamers en fluitende ketels. Hier wordt een kapotte focus weer een wapen en een verloren verhaal weer een route. Aan de horizon draaien de Spiegelvelden nog, maar hun licht bereikt de stad niet meer.','Je hebt de stormlens. Bereid je hier voor op de zoektocht naar de Oceaanverdeler.'],
 mirrors:['Licht in verkeerde handen','De spiegels volgen de zon alsof de Wereldbreuk nooit gebeurde. Hun kristallen voeden nu de wezens die het veld bewaken. Maak de collectoren vrij, dan kunnen de oude lichtbruggen weer genoeg kracht verzamelen.','Het zonnenet levert de energie voor de route door de Zoutcentrale naar de Rode Kilometer.'],
 brine:['Het water dat niet stroomt','In de pekelketels trilt een koele blauwe gloed. Ooit stuurden ze drinkwater langs de hete handelsweg; nu houdt hun bewaking iedere reiziger tegen. Ergens achter het zout hoor je opnieuw een druppel vallen.','Je maakt de watervoorraad vrij voor de oversteek naar de Oceaanverdeler.'],
 kilometer:['Een getij in een kristal','Zelfs hier, ver van zee, bewegen de blauwe wijzers met het getij. Twee koelstations bewaren samen het ritme van de oceaan. Kalibreer ze, maar wees klaar: de bewakers herkennen jouw magie nog als een indringer.','De Oceaanverdeler is de tweede sleutel. Hij kan de ontregelde waterstromen weer op elkaar afstemmen.'],
 forest:['Waar de kabels wortels werden','Licht loopt door de wortels langs het pad. De Veldmakers noemen het geen machine meer, maar een bos dat oude bevelen droomt. Verderop bewaart het Kasfront de kiemen waarmee je het levende archief kunt openen.','Na storm en getij zoek je de Biosfeersleutel: Aurelia moet ook begrijpen wat er nog leeft.'],
 glass:['De laatste kiemen','Achter gebarsten glas groeien bladeren met zilveren nerven. De kiemculturen zijn niet verdwenen; hun bewakers beschermen ze alleen tegen alles wat beweegt. Het levende netwerk heeft deze kiemen nodig om je te herkennen.','Maak de biokoepel vrij en open daarmee de route naar de bioarchieven van het Zoutwoud.'],
 saltwood:['Het archief dat ademt','Wanneer je dichterbij komt, openen de bladeren zich als bladzijden. Twee bioarchieven herinneren zich hoe de wereld bloeide. Hun stemmen moeten tegelijk terugkeren voordat de Biosfeersleutel zich laat vinden.','Dit is de derde sleutel. Zonder het levende archief zou een herstelde wereld opnieuw onbewoonbaar kunnen worden.'],
 vault:['Een bevel met een keerzijde','In de kluis ligt een verzegeld protocol. Het vertelt hoe de drie sleutels aan Aurelia worden gekoppeld, maar ook hoe de ingreep weer gestopt kan worden. De kluisbewaker heeft zijn wacht nooit opgegeven.','Berg het Aurelia-protocol: de sleutels openen de weg, het protocol vertelt hoe je de Kern veilig verbindt.'],
 skybridge:['Boven de storm','Door de wolken zie je voor het eerst de Aurelia-spits. De drie sleutels reageren op haar licht, maar het signaal breekt boven de Buitenzee. De Stormhaven bewaart de verbinding voor de laatste oversteek.','Bevoorraad je en maak het stormplatform vrij. Je bent dicht bij Aurelia, maar haar uplink ontbreekt nog.'],
 harbor:['De stem van de overkant','Het verlaten platform kraakt in de wind. Boven de masten flikkert een signaal: Aurelia probeert nog steeds antwoord te krijgen. Haar bewakers schermen de uplink af alsof de hele wereld een indringer is.','Bevrijd de uplink. Daarmee kan het Wolkenarchief de laatste stormmeting doorgeven.'],
 clouds:['Tussen de bladzijden van de wind','Doorzichtige archiefplaten draaien boven het platform. Iedere plaat bewaart een storm, een verloren route, een waarschuwing. Maak het archief vrij; Aurelia heeft deze laatste meting nodig voordat jij haar Wachter tegemoet gaat.','Het Wolkenarchief toetst de route boven de storm. Dit is de laatste beveiliging vóór de Aurelia-spits.'],
 aurelia:['De Wachter en de belofte','De drie sleutels zweven naar de Gouden Kern. Tussen jou en haar licht staat de Wachter, gebouwd om een verkeerde ingreep tegen te houden. Hij kent je bedoelingen niet. Laat zien dat je zijn proef kunt doorstaan.','Versla de Gouden Wachter en verbind de sleutels. Aurelia kan dan voor het eerst sinds de Wereldbreuk weer antwoorden.'],
 'metro-refuge':['Een antwoord uit de diepte','Aurelia is ontwaakt, maar haar licht bereikt de ondergrond niet. In het Onderstation kloppen leidingen tegen de muren. Twee regionale regelaars blijven stil: de eerste ligt onder de verdronken stad.','Zoek de oceaanregelaar in het diepe pompnet. Alleen de Spits herstellen was nog niet genoeg.'],
 sluice:['De deur onder de vloedlijn','Achter de sluis flikkert een lichtlijn die al jaren niemand heeft gevolgd. Drukduikers houden de doorgang dicht. Maak ruimte, dan voert de lijn je naar het Verzonken Spoornet.','De sluis is de eerste beveiliging op de route naar de oceaanregelaar.'],
 railworks:['De laatste trein reed naar beneden','De rails verdwijnen in het donker. Oude wissels sturen nog stroom naar de Diepwaterkamer, maar hun bewakers knippen iedere verbinding door. Volg de vonken langs het spoor.','Bevrijd het spoornet zodat je de Diepwaterwacht en de oceaanregelaar kunt bereiken.'],
 deepwater:['Wat de zee bewaart','Hier klinkt iedere stap alsof je onder water loopt. De Diepwaterwacht staat voor de oceaanregelaar; zijn drukgolven laten zelfs het steen buigen. Dit is geen verlaten schatkamer. Het is een slot dat nog werkt.','Versla de Diepwaterwacht en maak de oceaanregelaar vrij. Daarna wacht Koelhof met de laatste route.'],
 'cooling-refuge':['De wijk die de zon trotseert','Koperen luifels werpen koele schaduwen over de markt. De ambachtslieden weten welke uitrusting de hete grensroute overleeft. Aan het einde daarvan staat een toren die de laatste regelaar bewaakt.','Versterk je uitrusting. De thermische regelaar is de laatste verbinding die Aurelia nog mist.'],
 heatworks:['Waar de grond nog gloeit','Rode lichtaders lopen onder het steen. Ooit hield de warmtewissel de grenslanden koel; nu jagen haar bewakers vuur over de route. Iedere vrije strook brengt je dichter bij de toren.','Bevrijd de warmtewissel om de route naar de condensatorvelden te openen.'],
 condensers:['De lucht wordt zwaar','Boven de condensatoren hangen druppels die niet vallen. Storm, gif en hitte hebben zich rond de oude leidingen verzameld. De toren krijgt pas stroom wanneer deze laatste bewaking is doorbroken.','Maak het condensatorveld vrij. De thermische regelaar ligt nu één gevecht verder.'],
 tower:['Het laatste slot','De Torenwachter draagt het licht van duizend zomers in zijn borst. Hij bewaakt de laatste regelaar alsof daarbuiten niets meer bestaat. Achter hem wacht een wereld die meer kan worden dan ruïnes en schuilplaatsen.','Versla de Torenwachter en verbind de thermische regelaar. Dan is het hele netwerk van Aurelia verbonden.'],
 salvage:['Schatten tussen de getijden','Een bergerslint hangt aan een roestige paal. Onder het aangespoelde schroot liggen bruikbare kristallen, maar ook wezens die zich hier hebben genesteld. Je kunt terugkomen; het getij brengt telkens iets nieuws.','Een optionele berging levert schroot en een vondst op. Ze versterkt je uitrusting, zonder de hoofdroute te vervangen.'],
 depot:['De voorraad die niemand kwam halen','Op de kisten staat nog het zegel van een verdwenen karavaan. De bewakers wachten niet meer op een eigenaar. Jij kunt de voorraad beter gebruiken voor de volgende lichtbrug.','Een herhaalbare berging voor schroot en uitrusting. De vijanden groeien met je mee.'],
 'workshop-v6':['Een werkplaats achter sloten','Tussen de stilgevallen persen ligt een verbondsarchief. Iemand probeerde hier de oude magie in nieuwe focussen te vangen. De bewaking staat nog op scherp.','Optionele berging: bevrijd de werkplaats voor schroot en een vondst.'],
 'bounty-spore':['De prijs van een sporenkroon','Sera waarschuwde je voor de adem boven het bassin. Eén groot wezen heeft de bergplaats opgeëist. Zijn gif is berucht, maar de vondsten die het bewaakt maken de omweg de moeite waard.','Een zwaar, herhaalbaar baascontract. Kies bij Sera voor meer schroot of een betere kans op uitrusting.'],
 'bounty-solar':['Een schat die brandt','In de Zonneoven ligt goudkleurig stof dat nooit afkoelt. Eén oude bewaker laat het hele veld oplichten. Sera betaalt goed voor iemand die levend terugkeert.','Een zwaar, herhaalbaar baascontract. Het is een manier om sterker terug te komen wanneer de hoofdroute te zwaar wordt.'],
 'adventure-metro':['Drie onderdelen, één nieuwe kans','Milo heeft drie pomponderdelen op zijn kaart gemarkeerd. Zonder die stukken kan de kade haar oude leidingen niet repareren. Je hoeft geen heldenverhaal te vinden: iets heelhouden is hier al avontuur genoeg.','Een berging buiten de hoofdroute. Zoek de drie gemarkeerde punten en neem hun onderdelen mee.'],
 'adventure-caravan':['De karavaan zonder stemmen','De wagens staan nog in een kring, hun lantaarns gedoofd. Drie ladingen bleven achter toen de handelsweg verdween. De bergers in Vrijhaven kunnen iedere kist gebruiken.','Bevrijd drie bergingspunten en verzamel hun voorraad voor een extra beloning.'],
 'adventure-bio':['Het laboratorium luisterde terug','Onder het gebroken dak groeien planten door de oude instrumenten. Filters en een archiefkopie liggen op drie plekken verspreid. De gifdragers beschermen hier meer dan alleen hun territorium.','Een optionele expeditie voor onderdelen en schroot. Maak de drie bergingspunten vrij.'],
 'adventure-radar':['Een baken in de wind','De radar zendt nog een zwakke puls langs de wolken. Drie onderdelen kunnen hem weer bruikbaar maken voor de reizigers beneden. Bewakers hebben zich rond iedere vindplaats verzameld.','Berg alle drie de radaronderdelen. De terugpoort opent zodra de expeditie compleet is.'],
 groenkloof:['Een groene draad in het zand','Tussen glazen duinen ligt een wadi vol blauwgroene schaduw. Orin zegt dat er kristallen groeien waar de oude lichtbruggen de bodem raken. Achter de stad begint een route die niet op de hoofdkaart staat.','Een optionele omweg voor avontuur en uitrusting. Verken de wadi of beproef je build in de Glazen Duinen.'],
 'glass-dunes':['De duinen die zingen','Ieder kristal geeft een andere toon onder je voeten. De wezens in het zand volgen dat geluid; de Duinbreker hoort je van ver. Je zoekt geen nieuwe sleutel, maar kracht voor wat nog komt.','Een optionele arena. Doorsta de gevechtsgroepen en versla de Duinbreker voor een extra vondst.'],
 lanternwood:['Lantaarns zonder handen','Het bos draagt zijn eigen licht. Tess vertelt over een kristalwaterval waar de stroom ooit zuiver was, en een kroon die door een groot wezen wordt bewaakt. Sommige routes zijn niet nodig, maar wel de moeite waard.','Verken een optionele streek, verzamel vondsten en zoek de route naar de Kristalwaterval.'],
 crystalfalls:['Wat de stroom heeft gevormd','Het water valt in dunne, lichtgevende draden. Kristalwezens bewegen alsof ze deel van de waterval zijn. Hun bewaker houdt de stroom in een greep van steen.','Versla de bewaking van de Kristalwaterval. Daarmee komt het gevecht om de Koperen Kroon vrij.'],
 coppercrown:['De kroon heeft een eigenaar','Tussen de wortels ligt een ring van koperkleurige bladeren. De Kroonbeer waakt erover, oud genoeg om de Wereldbreuk te hebben gezien. Zijn schat neem je niet mee zonder zijn proef te doorstaan.','Een optionele zware baas. Daag de Kroonbeer uit voor bijzondere uitrusting.'],
 'rain-garden':['De tuin boven de oude stad','Tussen de bladeren vind je sporen van een werkplaats die hier ooit water ving. Linde heeft haar regenkompas nodig om dat werk opnieuw te beginnen. Misschien ligt het nog waar haar tuin het licht zocht.','Verken de tuinen voor Lindes regenkompas. Samen met de ateliersleutel opent het een specialistische werkplaats.'],
 'quiet-apartments':['De deur die bleef wachten','In de stille woningen staan nog schoenen naast de deuren. Milo herinnert zich een sleutel die een ambachtsvrouw hier achterliet. Volg haar sporen; sommige verloren plekken kunnen weer open.','Zoek de ateliersleutel. Breng die en het regenkompas naar Milo in Vrijhaven.'],
 'hidden-atelier':['Magie in de naden','Linde schuift een fonkelend zegel over haar werkbank. Waar anderen alleen een mantel zien, ziet zij ruimte voor bescherming tegen vuur, water en gif. De werkplaats heeft eindelijk weer bezoekers.','Weef elementweerstand in je uitrusting, of spaar voor Lindes bijzondere recepten.'],
 'trial-tide':['De proef van het getij','Aurelia bewaart echo’s van haar oude verdediging. Deze getijdenproef laat je opnieuw door die echo’s heen breken. Deze keer zoek je geen sleutel: je jaagt op je eigen beste tijd.','Herhaalbare tijdproef na Aurelia: vier golven, een eindbaas en je eigen record.'],
 'trial-glass':['De proef van het glas','De spiegels van Aurelia kunnen een heel slagveld herinneren. In deze proef bewegen de echo’s als splinters rond je staf. Hoe scherp is de build die je onderweg hebt gemaakt?','Herhaalbare tijdproef: doorsta vier golven en verbeter je tijd op de gekozen moeilijkheid.'],
 'trial-null':['De proef van de stilte','Waar het netwerk zwijgt, blijft alleen jouw magie over. Aurelia vormt hier haar zwaarste echo’s tot één arena. Je hebt de wereld verbonden; nu kun je laten zien hoe goed je haar hebt leren lezen.','Een herhaalbare eindspelproef voor je build en je tijdrecord.']
};
export const MEASUREMENT_AREAS=new Set(['ring','kilometer','saltwood']);
for(const [id,r]of Object.entries(NEXT_ROOMS))JOURNEY_SCENES[id]=[r.name,r.body,'Een rustig huis om te verkennen. De hoofdroute wacht buiten.'];
export function campaignAim(state){
 const count=[0,1,2].filter(id=>state.cores?.includes(id)).length;
 if(state.expansionCompleted)return 'Aurelia verbonden · nieuwe avonturen en tijdproeven';
 if(state.completed||state.cores?.includes(3))return state.zone>=5?'Laatste verbinding · thermische regelaar':'Aurelia antwoordt · herstel de regionale regelaars';
 return ['Zoek de Atmosferische lens · eerste sleutel','Zoek de Oceaanverdeler · tweede sleutel','Zoek de Biosfeersleutel · derde sleutel','Drie sleutels gevonden · bereik Aurelia'][count];
}
export function journeyEntry(id,state){
 const area=AREA_BY_ID[id],scene=JOURNEY_SCENES[id];if(!area||!scene)return null;
 const w=state.world||{};
 let goal;
 if(MEASUREMENT_AREAS.has(id))goal='Ga naar meetstation A of B en start de kalibratie. Versla per station twee bewakingsgolven, maak beide stations online en versla daarna de kernbewaker. Berg de sleutel bij de terugdoorgang.';
 else if(area.interior)goal='Praat met de bewoner. Neem daarna de deur terug naar buiten.';
 else if(area.safeExplore)goal=id==='hidden-atelier'?'Praat met Linde aan haar werkbank. Kies een elementzegel of bekijk haar bijzondere recepten.':id==='rain-garden'?'Volg de tuinpaden, zoek het regenkompas en bekijk de andere vondsten. Lever het samen met de sleutel bij Milo in.':'Doorzoek de woningen en berg de ateliersleutel. Lever beide vondsten bij Milo in Vrijhaven in.';
 else if(area.bounty)goal='Versla de contractbaas, verzamel je beloning en keer terug naar de handelspost. Je kunt dit contract opnieuw doen; de beloning volgt je keuze bij Sera.';
 else if(area.adventure)goal='Bevrijd de drie gemarkeerde bergingspunten en pak bij ieder punt het onderdeel met interactie. Verzamel je beloning en neem de terugpoort.';
 else if(area.endgame)goal='Versla vier golven inclusief de eindbaas. Je tijd loopt tijdens de proef; je beste resultaat wordt per moeilijkheid bewaard.';
 else if(['rooftops','vault'].includes(id))goal='Volg de route, versla de bewaker bij de verhaalvoorraadkist en open die kist met interactie. Daarna komt het volgende hoofdstuk vrij.';
 else if(id==='aurelia')goal='Versla de Gouden Wachter en alle overgebleven bewakers. Activeer Aurelia bij de gouden Kern met interactie.';
 else if(area.bossArena||id==='coppercrown')goal=id==='tower'?'Versla de Torenwachter. Verbind daarna de thermische regelaar bij de terugdoorgang met interactie.':'Versla de gebiedsbaas, verzamel je vondsten en keer terug via de vrijgekomen poort.';
 else if(area.side||area.biomeArena||area.natureArena)goal='Versla de gevechtsgroepen en de gebiedsbewaker. Pak je vondsten en gebruik de terugpoort zodra de arena vrij is.';
 else goal=id==='canal'?'Volg de gouden pijl naar de arenapoort van de Rietdelta. Je kunt eerst handelen en de kade verkennen.':'Handel en versterk je uitrusting. Volg daarna de gouden pijl naar het volgende hoofdstuk; zijpaden zijn optioneel.';
 // The replay page shows the current task, including a cleared arena or completed station.
 if(w.coreCollected&&MEASUREMENT_AREAS.has(id))goal='Deze sleutel is geborgen. Neem de terugdoorgang en volg vanuit de handelspost de volgende gouden route.';
 else if(w.sideDone&&!area.endgame)goal=id==='tower'&&!w.coreCollected?'De Torenwachter is verslagen. Verbind de thermische regelaar bij de terugdoorgang.':'Gebied vrijgemaakt. Verzamel je vondsten en keer terug via de poort. Vanuit de handelspost kun je verder reizen.';
 else if(MEASUREMENT_AREAS.has(id)&&w.relays?.every(r=>r.status==='online'))goal='Beide metingen zijn hersteld. Versla de kernbewaker en de overige bewakers; berg daarna de sleutel bij de terugdoorgang.';
 else if(w.trial?.done)goal='Tijdproef voltooid. Pak je beloning en neem de terugpoort. Je kunt vanuit de handelspost opnieuw starten.';
 else if(['rooftops','vault'].includes(id)&&w.storyCacheClaimed)goal='De verhaalvondst is geborgen. Volg de gouden pijl naar de volgende doorgang.';
 const chapter=STORY_ORDER.indexOf(id);
 return {id,title:scene[0],text:scene[1],why:scene[2],goal,aim:campaignAim(state),chapter:chapter<0?'OPTIONEEL AVONTUUR':'HOOFDSTUK '+(chapter+1)+' / '+STORY_ORDER.length,measurement:MEASUREMENT_AREAS.has(id),area:area.name,image:'assets/painted/previews/'+area.file};
}
