import {SPELLS,AREA_BY_ID} from './data.js?v=905';
import {makeItem,makeUniqueItem,statsText} from './loot.js?v=905';
export const MARKET_REGIONS=[
 {name:'Waterlijnhandel',specialty:'Getijdenfoci, waterbestendige veldpakken en snelle laarzen.',level:1,bases:['tidal-fork','tide-coat','reservoir','runner-boots','field-gloves','field-belt','storm-staff','cobalt-coat'],qualities:['common','common','uncommon','uncommon','uncommon','uncommon','rare','rare']},
 {name:'Schrootstation',specialty:'Zonnefoci, hittewerende kleding en condensortechniek.',level:4,bases:['amber-prism','cinder-coat','sun-compass','ash-boots','copper-gauntlets','solar-belt','prism','brass-jacket'],qualities:['uncommon','uncommon','uncommon','uncommon','uncommon','uncommon','rare','rare']},
 {name:'Veldmakers',specialty:'Levende foci, gifwerende bouwstukken en krachtige stormspreuken.',level:7,bases:['fork-focus','bloom-coat','seed-heart','quickstep-boots','thorn-gloves','medtech-belt','nav-astrolabe','storm-gloves'],qualities:['uncommon','uncommon','rare','uncommon','uncommon','rare','rare','epic']},
 {name:'Horizonpost',specialty:'Precisiefoci, stormuitrusting, Winterkroon en legendarische spaarstukken.',level:10,bases:['storm-staff','brass-coat','vector','runner-boots','storm-gloves','condenser-belt','prism','cobalt-coat'],qualities:['rare','rare','rare','rare','rare','rare','legendary','epic']}
];
MARKET_REGIONS.push(
 {name:'Onderstation',specialty:'Diepwaterfoci, drukpantser en kostbare oceanische meesterwerken.',level:15,bases:['pressure-focus','pressure-suit','turbine-heart','rime-boots','pressure-gloves','pressure-belt','prism','filter-hood'],qualities:['rare','rare','rare','rare','rare','rare','epic','epic']},
 {name:'Koelhof',specialty:'Thermische foci, koeltorenmantels en het sterkste veldwerk van de expeditie.',level:18,bases:['thermal-prism','cooling-jacket','cooling-core','thermal-boots','thermal-gloves','valve-belt','storm-staff','storm-crown'],qualities:['rare','rare','rare','rare','rare','rare','epic','epic']}
);
const routeBases={rooftops:['tide-staff','utility-coat','field-compass','field-boots','copper-gauntlets','field-belt','tidal-fork','runner-boots'],vault:['fork-focus','ranger-coat','seed-heart','quickstep-boots','thorn-gloves','medtech-belt','seed','bloom-coat']};
export const SPELL_OFFERS={prism:{id:'prism',price:650,minZone:1,level:5,location:'Focusmaker vanaf Vrijhaven',role:'Mobiele kettingaanval · vier verschillende doelen',numbers:'70 beginschade · 18 mana · 1,2s · sprongen behouden 88% schade'},volt:{id:'volt',price:1200,minZone:2,level:8,location:'Focusmaker vanaf de Groene Corridor',role:'Gerichte lans · tot drie doelen op één lijn',numbers:'90 schade · 24 mana · 1,65s · natte doelen geleiden'},cryo:{id:'cryo',price:1800,minZone:3,level:11,location:'Focusmaker bij Horizonpost',role:'Gebiedscontrole · zware vorstexplosie met nasplinters',numbers:'95 schade + 2 × 16 naschade · 30 mana · 5,5s'}};
// Fixed premium pieces: the price buys a known build upgrade, never a reroll.
export const INVESTMENTS=[
 [{id:'canal-focus',base:'tidal-fork',name:'Focus van de Hoge Kade',slot:'weapon',price:360,level:4,stats:{power:.12,tide:.18,regen:1}}, {id:'canal-coat',base:'cobalt-coat',name:'Versterkt Waterlijnpak',slot:'suit',price:420,level:4,stats:{hp:32,armor:.06,poisonResist:.08}}, {id:'canal-lens',base:'reservoir',name:'Diep Condenshart',slot:'relic',price:340,level:4,stats:{mana:30,regen:3}}, {id:'canal-boots',base:'runner-boots',name:'Kadepatrouillelaarzen',slot:'boots',price:320,level:4,stats:{speed:.16,dash:.12}}, {id:'canal-gloves',base:'storm-gloves',name:'Precisiegeleiders',slot:'gloves',price:300,level:4,stats:{power:.08,crit:.055}}, {id:'canal-belt',base:'field-belt',name:'Gordel van de Dijkwacht',slot:'belt',price:330,level:4,stats:{hp:18,mana:18,armor:.035}}],
 [{id:'heat-focus',base:'amber-prism',name:'Focus van de Hittekoepel',slot:'weapon',price:750,level:7,stats:{power:.18,ember:.24,crit:.04}}, {id:'heat-coat',base:'cinder-coat',name:'Thermisch Lamellenpak',slot:'suit',price:800,level:7,stats:{hp:48,armor:.1,fireResist:.16}}, {id:'heat-lens',base:'sun-compass',name:'Transportcondensator',slot:'relic',price:680,level:7,stats:{mana:42,regen:4,comboCharge:.12}}, {id:'heat-boots',base:'ash-boots',name:'Lopers van de Rode Kilometer',slot:'boots',price:650,level:7,stats:{speed:.18,dash:.18,fireResist:.1}}, {id:'heat-gloves',base:'copper-gauntlets',name:'Koperstorm Handschoenen',slot:'gloves',price:700,level:7,stats:{storm:.2,power:.08,crit:.065}}, {id:'heat-belt',base:'solar-belt',name:'Koelnetgordel',slot:'belt',price:650,level:7,stats:{hp:24,armor:.055,fireResist:.1}}],
 [{id:'grove-focus',base:'storm-staff',name:'Focus van de Wolkenlijn',slot:'weapon',price:1250,level:10,stats:{power:.22,storm:.24,chain:1}}, {id:'grove-coat',base:'bloom-coat',name:'Gesloten Biosfeerpak',slot:'suit',price:1200,level:10,stats:{hp:62,armor:.11,poisonResist:.2}}, {id:'grove-lens',base:'nav-astrolabe',name:'Levend Mananet',slot:'relic',price:1100,level:10,stats:{mana:54,regen:5,poisonResist:.08}}, {id:'grove-boots',base:'quickstep-boots',name:'Corridorloopwerk',slot:'boots',price:1050,level:10,stats:{speed:.21,dash:.22,poisonResist:.12}}, {id:'grove-gloves',base:'thorn-gloves',name:'Biosfeerfocus Handschoenen',slot:'gloves',price:1100,level:10,stats:{power:.15,crit:.08,poisonResist:.08}}, {id:'grove-belt',base:'medtech-belt',name:'Gordel van het Kiemarchief',slot:'belt',price:1000,level:10,stats:{hp:35,recovery:.8,poisonResist:.12}}],
 [{id:'horizon-focus',base:'prism',name:'Focus van de Stormgrens',slot:'weapon',price:1650,level:13,stats:{power:.28,crit:.08,storm:.15}}, {id:'horizon-coat',base:'brass-coat',name:'Aurelia Expeditiepantser',slot:'suit',price:1800,level:13,stats:{hp:80,armor:.15,stormResist:.2}}, {id:'horizon-lens',base:'reservoir',name:'Driekerncondensator',slot:'relic',price:1500,level:13,stats:{mana:64,regen:6,comboCharge:.2}}, {id:'horizon-boots',base:'runner-boots',name:'Stormbruglopers',slot:'boots',price:1450,level:13,stats:{speed:.24,dash:.25,waterResist:.16}}, {id:'horizon-gloves',base:'storm-gloves',name:'Handen van de Uplink',slot:'gloves',price:1550,level:13,stats:{power:.19,crit:.1,stormResist:.12}}, {id:'horizon-belt',base:'condenser-belt',name:'Gordel van de Laatste Route',slot:'belt',price:1450,level:13,stats:{mana:30,hp:38,armor:.07}}]
];
INVESTMENTS.push(
 [{id:'deep-focus',base:'pressure-focus',slot:'weapon',name:'Stemvork van de Drukgrens',price:2400,level:17,stats:{power:.55,tide:.5,regen:2}}, {id:'deep-coat',base:'pressure-suit',slot:'suit',name:'Diepwater Expeditiepantser',price:2500,level:17,stats:{hp:140,armor:.24,waterResist:.28}}, {id:'deep-lens',base:'turbine-heart',slot:'relic',name:'Hart van het Pompnet',price:2200,level:17,stats:{mana:90,regen:9,waterResist:.18}}, {id:'deep-boots',base:'rime-boots',slot:'boots',name:'Lopers van de Vloedlijn',price:2050,level:17,stats:{speed:.38,dash:.34,waterResist:.20}}, {id:'deep-gloves',base:'pressure-gloves',slot:'gloves',name:'Drukgrensgeleiders',price:2200,level:17,stats:{power:.27,crit:.14,waterResist:.16}}, {id:'deep-belt',base:'pressure-belt',slot:'belt',name:'Pompnet Bevoorradingsgordel',price:2050,level:17,stats:{hp:58,mana:44,armor:.10}}],
 [{id:'tower-focus',base:'thermal-prism',slot:'weapon',name:'Prisma van de Laatste Warmte',price:3300,level:20,stats:{power:.65,ember:.6,crit:.09}}, {id:'tower-coat',base:'cooling-jacket',slot:'suit',name:'Gesloten Koeltorenpak',price:3500,level:20,stats:{hp:170,armor:.28,fireResist:.30}}, {id:'tower-lens',base:'cooling-core',slot:'relic',name:'Thermisch Veldhart',price:2900,level:20,stats:{mana:108,regen:11,recovery:1.5}}, {id:'tower-boots',base:'thermal-boots',slot:'boots',name:'Koeltorensprint Laarzen',price:2750,level:20,stats:{speed:.43,dash:.4,fireResist:.24}}, {id:'tower-gloves',base:'thermal-gloves',slot:'gloves',name:'Handen van de Thermische Regelaar',price:2900,level:20,stats:{power:.32,crit:.17,fireResist:.18}}, {id:'tower-belt',base:'valve-belt',slot:'belt',name:'Laatste Reserve Veldgordel',price:2750,level:20,stats:{hp:70,mana:50,armor:.11}}]
);
// Saving targets are deliberate multi-chapter upgrades, with useful build stats.
for(let zone=0;zone<4;zone++)for(const spec of INVESTMENTS[zone]){
 const statBoost=[1.65,1.5,1.35,1.25][zone],priceBoost=[2.5,1.9,1.65,1.6][zone];
 spec.price=Math.round(spec.price*priceBoost/25)*25;
 for(const [key,value]of Object.entries(spec.stats))if(key!=='chain')spec.stats[key]=Number((value*(['speed','dash','crit'].includes(key)?1.15:statBoost)).toFixed(3));
}
for(let zone=1;zone<INVESTMENTS.length;zone++)for(const spec of INVESTMENTS[zone]){const previous=INVESTMENTS[zone-1].find(i=>i.slot===spec.slot);spec.price=Math.max(spec.price,previous.price+200);}
export function marketStock(g,zone,areaId){
 const region=MARKET_REGIONS[zone],bases=routeBases[areaId]||region.bases,level=region.level+(routeBases[areaId]?2:0);
 const stock=bases.map((baseId,i)=>{const item=makeItem({rng:g.rng,baseId,level:level+(i>=6?1:0),rarity:region.qualities[i],uid:++g.idCounter});
  if(item.rarity==='legendary')item.price=4200;
  if(i>=6)item.signature=true;return item;});
 const head=makeItem({rng:g.rng,baseId:['field-cap','sentinel-helm','filter-hood','storm-crown','sentinel-helm','storm-crown'][zone],level,rarity:zone>=3?'rare':'uncommon',uid:++g.idCounter});stock.push(head);
 for(const spec of INVESTMENTS[zone]){const item={id:spec.base,art:spec.base,uid:++g.idCounter,slot:spec.slot,name:spec.name,rarity:'epic',level:spec.level,requiredLevel:Math.max(2,spec.level-(spec.level>=18?4:spec.level>=15?3:2)),stats:{...spec.stats},price:spec.price,enhance:0,affixes:['Handelsmeesterwerk'],signature:true,investment:spec.id};item.text=statsText(item);stock.push(item);}
 const headSpec={base:['field-cap','sentinel-helm','filter-hood','storm-crown','sentinel-helm','storm-crown'][zone],price:[750,1150,1600,2000,2550,3400][zone],level:[4,7,10,13,17,20][zone]},premiumHead=makeItem({rng:g.rng,baseId:headSpec.base,level:headSpec.level,rarity:'epic',uid:++g.idCounter});premiumHead.price=headSpec.price;premiumHead.signature=true;premiumHead.investment='head-'+zone;premiumHead.name=['Kap van de Hoge Kade','Helm van de Hittekoepel','Kap van de Biosfeer','Diadeem van de Stormgrens','Helm van de Diepte','Kroon van het Koelnet'][zone];premiumHead.stats={hp:26+zone*18,armor:.05+zone*.012,[zone>=4?(zone===4?'waterResist':'fireResist'):zone===2?'poisonResist':'stormResist']:.06+zone*.02};if(zone>=4)premiumHead.stats={hp:zone===4?72:90,armor:zone===4?.14:.17,[zone===4?'waterResist':'fireResist']:zone===4?.24:.26};premiumHead.text=statsText(premiumHead);stock.push(premiumHead);
 if(zone>=2){const id=zone===2?'filter':'crystal',item=makeUniqueItem(id,zone===2?10:zone===3?13:zone===4?17:20,++g.idCounter);item.price=zone===2?1550:zone===3?2300:zone===4?3400:4400;item.signature=true;item.investment='unique-'+id;stock.push(item);}
 if(areaId==='groenkloof'){const item=makeUniqueItem('horizonDiadem',20,++g.idCounter);item.price=8500;item.chase=true;item.signature=true;item.investment='horizon-diadem';stock.push(item);}
 return stock;
}
const REGIONAL_NAMES=[['Mara','Jules','Inez'],['Ravi','Ada','Bo'],['Elow','Nils','Sanne'],['Veyra','Daan','Rook'],['Nami','Omar','Vika'],['Lyra','Sem','Edda']];
export function regionalService(areaId,service){const area=AREA_BY_ID[areaId],r=MARKET_REGIONS[area.zone],role=service.file==='smith'?0:service.file==='outfitter'?1:2;return {name:REGIONAL_NAMES[area.zone][role]+' · '+service.title,region:r.name,text:r.specialty+' '+service.text};}
export const MarketRules={
 spellOffers(){const service=this.currentService();return service?.id==='smith'?Object.values(SPELL_OFFERS).filter(o=>this.state.zone>=o.minZone):[];},
 buySpell(id){const offer=this.spellOffers().find(o=>o.id===id),p=this.state.player;if(!this.canTrade()||!offer||p.skills.includes(id)||p.level<offer.level||p.scrap<offer.price)return false;
  p.scrap-=offer.price;p.skills.push(id);this.notice(SPELLS[id].name+' geleerd · plaats zelf via K',SPELLS[id].color);this.emit('purchase',{name:SPELLS[id].name,cost:offer.price,icon:id,detail:'Geleerd · plaats de spreuk in je skillsmenu'});this.emit('level');this.checkpoint();return true;
 }
};
