import {AREA_BY_ID,ENEMIES,WORLD} from './data.js?v=903';
import {NATURE_ENEMIES,NATURE_LANDMARKS} from './nature-content.js?v=903';
import {launchEnemyLob} from './enemy-combat.js?v=903';
const dist=(a,b)=>Math.hypot(a.x-b.x,(a.y-b.y)*1.15);
const unit=(x,y)=>{const n=Math.hypot(x,y)||1;return {x:x/n,y:y/n};};
export function tuneNatureEnemy(e,area,playerLevel){if(!area?.natureArena)return e;const base=ENEMIES[e.type],growth=1+Math.min(6,Math.max(0,playerLevel-14))*.045;e.level=area.itemLevel;e.hp=e.maxHp=Math.round(base.hp*(base.boss?3.05:4.25)*growth);e.damageMultiplier=(area.natureBoss?2.25:2.15)*Math.sqrt(growth);e.speedMultiplier=1.06;e.cooldownMultiplier=.79;e.balanceVersion=83;return e;}
export const NatureRules={
 createNatureWorld(w,area){w.nature={wave:1,paid:false};w.sideRound=1;w.sideDone=false;w.coreCollected=true;w.relays=[];w.hazards=[];w.loot=[];w.gate={x:area.exit[0]*WORLD.width,y:area.exit[1]*WORLD.height,open:false,eliteSpawned:false};this.spawnNatureWave(w,area);},
 spawnNatureWave(w,area){const types=area.natureBoss?['crownbear']:w.nature.wave===1?['mossback','sunnewt','windowl','sunnewt','windowl']:['windowl','mossback','sunnewt','windowl','mossback','sunnewt'],positions=[[1020,650],[1230,680],[900,870],[705,640],[1100,440],[1340,870]];for(const [i,type]of types.entries()){const [x,y]=positions[i],e=this.placeSummon(this.makeEnemy(type,x,y,false,w.nature.wave>1));e.natureEnemy=true;if(area.natureBoss)e.guardian=true;w.enemies.push(e);}},
 completeNatureArena(){const s=this.state,w=s.world,a=AREA_BY_ID[s.area];if(!w.nature||w.nature.paid||s.mode!=='playing'||w.enemies.some(e=>!e.dead))return false;
  if(!a.natureBoss&&w.nature.wave===1){w.nature.wave=2;w.sideRound=2;this.spawnNatureWave(w,a);this.notice('Kristalwaterval · tweede groep · blijf tussen de vuurvelden bewegen');return true;}
  w.nature.paid=true;w.sideDone=true;w.gate.open=true;w.gate.eliteSpawned=true;s.player.scrap+=a.reward;s.natureVictories||={};s.natureVictories[s.area]=(s.natureVictories[s.area]||0)+1;
  if(!a.natureBoss)w.loot.push({id:++this.idCounter,x:w.gate.x-75,y:w.gate.y+55,type:'loot',profile:'expedition',expeditionReward:true});this.notice(a.name+' vrij · +'+a.reward+' schroot'+(a.natureBoss?'':' · de Kroonbeer is bereikbaar via het Lantaarnwoud'),'#ffe0a1');this.emit('relaydone');return true;
 },
 planNatureAttack(e){if(!NATURE_ENEMIES[e.type])return false;const p=this.enemyTarget(e),target={x:p.x,y:p.y},dir=unit(p.x-e.x,(p.y-e.y)*1.15);e.attacks=(e.attacks||0)+1;
  const sets={mossback:['shellRush','shellSlam'],sunnewt:['newtSpit','newtLob'],windowl:['owlGust','owlFan'],crownbear:['crownClaw','crownRing','amberRoots']},mode=sets[e.type][(e.attacks-1)%sets[e.type].length],quick=['owlGust','newtSpit'].includes(mode),total=quick?.35:mode==='crownClaw'?.65:mode==='shellRush'?.8:1.15;e.windup={mode,target,dir,total,timer:total,quick};if(['newtLob','amberRoots'].includes(mode))e.windup.targets=mode==='newtLob'?[target]:[target,{x:target.x-dir.y*165,y:target.y+dir.x*165/1.15},{x:target.x+dir.y*165,y:target.y-dir.x*165/1.15}];this.emit('windup',{type:e.type});return true;
 },
 executeNatureAttack(e){if(!NATURE_ENEMIES[e.type]||!e.windup)return false;if(this.inCamp())return true;const s=this.state,w=e.windup,base=ENEMIES[e.type],damage=base.damage*(e.damageMultiplier||1),add=t=>s.world.threats.push({id:++this.idCounter,source:e.id,age:0,damage,element:base.element,...t});
  if(w.mode==='shellRush'){e.rush={dir:w.dir,life:.28,damage,element:'physical',hit:false};this.effect('slash',e.x,e.y,{dir:w.dir,radius:110,color:base.color,element:'metal',life:.35});}
  if(['shellSlam','crownClaw'].includes(w.mode)){const r=w.mode==='shellSlam'?140:155,n=unit(s.player.x-e.x,(s.player.y-e.y)*1.15);if(dist(s.player,e)<r&&(w.mode==='shellSlam'||n.x*w.dir.x+n.y*w.dir.y>.15))this.hurtPlayer(damage,'physical');this.hurtCompanions(e,r,damage);this.effect('element-impact',e.x,e.y,{element:base.element,radius:r,life:.45});}
  if(['newtSpit','owlGust','owlFan'].includes(w.mode)){const count=w.mode==='owlFan'?3:1;for(let i=0;i<count;i++){const a=Math.atan2(w.dir.y,w.dir.x)+(i-(count-1)/2)*.24,speed=w.mode==='newtSpit'?500:630;s.projectiles.push({id:++this.idCounter,team:'enemy',type:'nature-bolt',x:e.x,y:e.y-30,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed/1.15,radius:7,damage:damage*(count===1?.85:1),gust:e.type==='windowl',life:2.2,age:0,trail:[]});}}
  if(['newtLob','amberRoots'].includes(w.mode)){for(const old of s.world.threats.filter(t=>t.source===e.id&&t.type==='bossPatch'))old.life=0;for(const target of w.targets){launchEnemyLob(this,e,target,{duration:.72,damage:damage*.7,radius:70,element:w.mode==='amberRoots'?'solar':'fire'});add({type:'bossPatch',...target,r:70,damage:damage*.55,arm:.9,life:4,tick:.7,element:'fire'});}}
  if(w.mode==='crownRing')add({type:'ring',x:e.x,y:e.y,r:65,width:24,speed:e.phase===2?300:245,life:1.7,hit:false,element:'solar'});this.emit('enemyattack',{enemy:e.type,mode:w.mode});return true;
 },
 updateNatureEnemy(e){if(e.type==='crownbear'&&e.phase===1&&e.hp<e.maxHp*.5){e.phase=2;e.cd=.6;e.cooldownMultiplier*=.84;this.notice('Kroonbeer · de amberkroon ontwaakt','#ffe0a1');this.effect('nova',e.x,e.y,{element:'solar',radius:100,life:.45});this.emit('bossphase',{enemy:e.type,phase:2});}},
 updateNatureExploration(){const s=this.state;if(s.area!=='lanternwood')return;s.natureDiscoveries||=[];for(const point of NATURE_LANDMARKS){if(s.natureDiscoveries.includes(point.id)||dist(s.player,point)>80)continue;s.natureDiscoveries.push(point.id);s.player.scrap+=25;this.notice(point.name+' ontdekt · +25 schroot','#cfe5ad');this.effect('relay',point.x,point.y,{radius:60,color:'#d6e8ac',life:.6});}},
};
