import {spellInsight} from './build-insights.js?v=901';
import {EQUIPMENT_SLOT_NAMES} from './equipment-slots.js?v=901';
import {RESISTANCES} from './resistances.js?v=901';
import {itemMark,protectedItem,markActions} from './item-marks.js?v=901';
import {SLOT_NAMES,RARITIES,SPELLS} from './data.js?v=901';
import {sellValue,statsText} from './loot.js?v=901';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=i=>'<img class="painted-item" src="assets/items/'+(i.art||i.id)+'.webp" alt="" draggable="false">';
export function visibleSellItems(p,filters={}){return p.inventory.filter(i=>(!filters.slot||filters.slot==='all'||i.slot===filters.slot)&&(!filters.rarity||filters.rarity==='all'||i.rarity===filters.rarity)&&(!filters.status||filters.status==='all'||filters.status==='available'&&!protectedItem(i)||itemMark(i)===filters.status)).sort((a,b)=>RARITIES[a.rarity].rank-RARITIES[b.rarity].rank||a.slot.localeCompare(b.slot)||a.level-b.level||a.uid-b.uid);}
export const sellableItems=items=>items.filter(i=>!protectedItem(i));
function sellBody(engine,selection,filters){
 const p=engine.state.player,items=visibleSellItems(p,filters),picked=p.inventory.filter(i=>selection.has(i.uid)&&!protectedItem(i)),total=picked.reduce((sum,i)=>sum+sellValue(i),0);
 const options=(values,current)=>values.map(([id,label])=>'<option value="'+id+'" '+(id===current?'selected':'')+'>'+label+'</option>').join('');
 let html='<div class="sell-toolbar"><label>Uitrustingstype<select data-sell-filter="slot">'+options([['all','Alle uitrusting'],...Object.entries(SLOT_NAMES)],filters.slot)+'</select></label><label>Zeldzaamheid<select data-sell-filter="rarity">'+options([['all','Alle zeldzaamheden'],...Object.entries(RARITIES).filter(([id])=>id!=='field').map(([id,r])=>[id,r.name])],filters.rarity)+'</select></label><label>Markering<select data-sell-filter="status">'+options([['all','Alle items'],['available','Verkoopbaar'],['junk','Verkoopwaar'],['favorite','Bewaard']],filters.status||'all')+'</select></label></div>';
 html+='<div class="sell-selection"><div><strong data-sell-summary aria-live="polite" aria-atomic="true">'+picked.length+' geselecteerd · +'+total+' schroot</strong><small>'+items.length+' van '+p.inventory.length+' rugzakitems zichtbaar · bewaarde en gedragen uitrusting blijven beschermd</small></div><button data-sell-all="true" '+(!sellableItems(items).length?'disabled':'')+'>Selecteer zichtbare items</button><button data-sell-junk="true">Selecteer verkoopwaar</button><button data-sell-clear="true" '+(!picked.length?'disabled':'')+'>Wis selectie</button></div>';
 html+='<div class="sell-list">'+items.map(item=>'<div class="sell-row"><button class="sell-item '+(selection.has(item.uid)?'selected':'')+'" data-shop-item="'+item.uid+'" data-rarity="'+item.rarity+'" '+(protectedItem(item)?'disabled':'')+' aria-pressed="'+(selection.has(item.uid)&&!protectedItem(item))+'"><span class="sell-check" aria-hidden="true">'+(protectedItem(item)?'★':selection.has(item.uid)?'✓':'')+'</span><span class="sell-art">'+art(item)+'</span><span class="sell-info"><strong>'+escape(item.name)+(item.enhance?' +'+item.enhance:'')+'</strong><small>'+RARITIES[item.rarity].name+' · '+SLOT_NAMES[item.slot]+' · NIV. '+item.level+'</small><span>'+escape(statsText(item))+'</span></span><b>+'+sellValue(item)+'<small>SCHROOT</small></b></button>'+markActions(item)+'</div>').join('')+'</div>';
 if(!items.length)html+='<p class="empty-bag">'+(!p.inventory.length?'Je rugzak is leeg.':'Geen items met deze filters.')+'</p>';
 return html;
}
// Selection is local UI state: keep the rows, scroll position and active control.
export function updateSellSelection(root,p,selection,sellButton){
 const picked=p.inventory.filter(i=>selection.has(i.uid)&&!protectedItem(i)),total=picked.reduce((sum,i)=>sum+sellValue(i),0);
 for(const row of root.querySelectorAll('[data-shop-item]')){
  const item=p.inventory.find(i=>i.uid===Number(row.dataset.shopItem)),selected=selection.has(Number(row.dataset.shopItem))&&!protectedItem(item);row.disabled=protectedItem(item);row.classList.toggle('selected',selected);row.setAttribute('aria-pressed',String(selected));row.querySelector('.sell-check').textContent=protectedItem(item)?'★':selected?'✓':'';
 }
 root.querySelector('[data-sell-summary]').textContent=picked.length+' geselecteerd · +'+total+' schroot';
 root.querySelector('[data-sell-clear]').disabled=!picked.length;
 sellButton.textContent='Verkoop geselecteerd ('+picked.length+') · +'+total+' schroot';sellButton.disabled=!picked.length;
}
export function shopBody(engine,tab,selected,sellUi={selection:new Set(),filters:{slot:'all',rarity:'all'}}){
 const p=engine.state.player,w=engine.state.world,service=engine.currentService(),items=tab==='buy'?engine.serviceStock():tab==='sell'?p.inventory:Object.entries(p.equipment).filter(([,i])=>!i.empty).map(([slot,i])=>({...i,equippedSlot:slot}));
 let html='<div class="shop-intro" data-service="'+(service?.id||'smith')+'"><img src="assets/expedition/merchant.webp" alt="Handelaar"><div><strong>'+p.scrap+' SCHROOT</strong><p>'+escape(service?.text||'Koop, verkoop of versterk je uitrusting.')+'</p><small>Voorraad en aankopen blijven bewaard. Bijzondere stukken zijn beperkt; een nieuwe bezoekronde vult ze niet aan.</small></div></div>';
 const tabs=service?.id==='workshop'?[['forge','Versterken'],['sell','Verkopen']]:[['buy','Kopen'],['sell','Verkopen'],...(service?.forge?[['forge','Versterken']]:[]),...(engine.spellOffers().length?[['spells','Spreuken']]:[]),...(service?.id==='outfitter'?[['gamble','Loot loten']]:[])];
 html+='<div class="shop-tabs">'+tabs.map(([id,label])=>'<button data-shop-tab="'+id+'" class="'+(tab===id?'selected':'')+'">'+label+'</button>').join('')+'</div>';
 if(tab==='spells')return html+'<p class="menu-intro">Een blijvende investering. Je koopt de spreuk één keer en plaatst haar daarna zelf via K op links, rechts of 1–6. Je bestaande knoppen blijven bewaard.</p><div class="spell-market">'+engine.spellOffers().map(o=>{const spell=SPELLS[o.id],learned=p.skills.includes(o.id);return '<article><img class="painted-spell" src="assets/items/skill-'+o.id+'.webp" alt=""><div><small>EXCLUSIEF · NIV. '+o.level+'</small><h3>'+spell.name+'</h3><p>'+escape(spell.description)+'</p><p class="spell-numbers">'+escape(o.numbers)+'</p><div class="market-build"><small>MET JE HUIDIGE UITRUSTING</small>'+spellInsight(p,engine.stats(),o.id)+'<small>Vóór kritieke treffers, combo’s, bijzondere itemeffecten en vijandbescherming.</small></div><strong>'+o.price+' schroot</strong><button data-buy-spell="'+o.id+'" '+(learned||p.level<o.level||p.scrap<o.price?'disabled':'')+'>'+(learned?'Al geleerd':p.level<o.level?'Vereist niveau '+o.level:p.scrap<o.price?'Nog '+(o.price-p.scrap)+' schroot sparen':'Koop & leer spreuk')+'</button></div></article>';}).join('')+'</div>';
 if(tab==='gamble'){const result=w.shop.lastRoll;return html+'<div class="gamble-intro"><strong>Een vondst voor je build</strong><p>Kies een uitrustingstype. Iedere worp kost '+engine.gambleCost()+' schroot en geeft één willekeurig item. Je rust het daarna zelf uit.</p><p class="gamble-odds">Common 40% · Uncommon 36% · Rare 18% · Epic 5% · Legendary 1%</p><div class="gamble-slots">'+Object.entries(SLOT_NAMES).map(([slot,name])=>'<button data-gamble-slot="'+slot+'" '+(p.scrap<engine.gambleCost()||p.inventory.length>=48?'disabled':'')+'>'+name+'<small>'+engine.gambleCost()+' schroot</small></button>').join('')+'</div></div>'+(result?'<div class="gamble-result">'+art(result)+'<div><small>'+RARITIES[result.rarity].name+' · IN JE RUGZAK</small><strong>'+escape(result.name)+'</strong><p>'+escape(statsText(result))+'</p></div></div>':'');}
 if(tab==='forge'&&selected){const mode=sellUi.forgeMode||'base';html+='<div class="forge-choices"><h3>Kies je versterking</h3><p>Iedere keuze gebruikt één van drie versterkingen. Weerstand: +8 procentpunt per stap, maximaal 24% op één item en 60% totaal.</p>'+[['base','Basis verbeteren','field-staff'],...Object.entries(RESISTANCES).map(([id,r])=>[id,r.name+' +8%',r.art])].map(([id,label,file])=>'<button data-forge-mode="'+id+'" class="'+(mode===id?'selected':'')+'" aria-pressed="'+(mode===id)+'" '+(selected.enhance>=3||id!=='base'&&(selected.stats[id]||0)>=.24?'disabled':'')+'><img class="painted-item" src="assets/items/'+file+'.webp" alt=""><strong>'+label+'</strong></button>').join('')+'</div>'; }
 if(tab==='sell')return html+sellBody(engine,sellUi.selection,sellUi.filters);
 html+='<div class="shop-grid">'+items.map(item=>'<button class="shop-item '+(item.uid===selected?.uid?'selected':'')+'" data-shop-item="'+item.uid+'" data-rarity="'+item.rarity+'"><span>'+art(item)+'</span><div>'+(item.signature?'<small class="market-signature">'+(item.chase?'UITZONDERLIJK LEGENDARISCH · ÉÉN IN VOORRAAD':item.investment?'SPAARSTUK · VASTE BUILDSTATS':item.rarity==='legendary'?'LEGENDARISCH SPAARSTUK · ÉÉN IN VOORRAAD':'POSTSPECIALITEIT')+'</small>':'')+'<small>'+RARITIES[item.rarity].name+' · NIV. '+(item.level||1)+' · '+(item.equippedSlot?EQUIPMENT_SLOT_NAMES[item.equippedSlot]:SLOT_NAMES[item.slot])+'</small><strong>'+escape(item.name)+(item.enhance?' +'+item.enhance:'')+'</strong>'+((item.requiredLevel||1)>p.level?'<small class="level-requirement">Vereist spelersniveau '+item.requiredLevel+'</small>':'')+'<p>'+escape(statsText(item))+'</p><b>'+ (tab==='buy'?item.price+' schroot'+(p.scrap<item.price?' · nog '+(item.price-p.scrap)+' sparen':' · betaalbaar'):tab==='sell'?'Verkoop: '+sellValue(item)+' schroot':item.enhance>=3?'MAX. VERSTERKT':engine.forgeCost(item)+' schroot → +'+((item.enhance||0)+1))+'</b></div></button>').join('')+'</div>';
 if(!items.length)html+='<p class="empty-bag">'+(tab==='buy'?'Voorraad uitverkocht. De volgende handelspost heeft nieuwe spullen.':'Je rugzak is leeg.')+'</p>';
 return html;
}
