import {companionTraining} from './companion-upgrades.js?v=909';
import {summonAvailable,summonUnlockLevel} from './summon-progression.js?v=909';
import {ENEMIES} from './data.js?v=909';
const dist=(a,b)=>Math.hypot(a.x-b.x,(a.y-b.y)*1.15);
export const COMPANIONS={
 scout:{name:'Getijvossen',art:'companion-fox-v82',element:'tide',text:'Twee kwetsbare geestvossen schieten waterlicht. Maak vijanden nat voor je stormspreuken.',count:2,hp:34,life:18,damage:8,interval:1.1},
 guardian:{name:'Moszwijn',art:'companion-boar-v82',element:'physical',text:'Een stevig bosdier vangt projectielen op, vertraagt vijanden en slaat met zijn slagtanden.',count:1,hp:95,life:20,damage:5,interval:1.8},
 mender:{name:'Lichtmot',art:'companion-moth-v82',text:'Een kwetsbare lichtmot herstelt maximaal 24 leven per oproep. Verdiend via Ilya in Vrijhaven.',count:1,hp:42,life:16,damage:0,interval:2}
};
export const SummonRules={
 summonCompanions(){const s=this.state,p=s.player,early=p.level<10,profile=early?'scout':p.companionProfile||'scout',spirit=!early&&profile==='scout'&&this.hasUnique('spiritAmber'),spec=spirit?{...COMPANIONS.scout,count:1,hp:68,life:16,damage:22}:COMPANIONS[profile];
  if(!spec||!summonAvailable(p)||!p.skills.includes('summon'))return false;s.summons=[];p.summonTarget=null;const stats=this.stats(),scale=1+Math.min(.65,stats.power),count=early||spirit?1:spec.count+(profile==='scout'?stats.minionCount||0:0),training=companionTraining(p,profile),life=1,health=spec.hp*scale*(1+(stats.minionHealth||0)+(training.vitality||0)*.15);
  for(let i=0;i<count;i++){const unit={id:++this.idCounter,profile,early,spirit,companion:true,persistent:true,training:{...training},x:p.x+(i?45:-45),y:p.y+35,radius:17,hp:health,maxHp:health,life,maxLife:life,cd:.5+i*.3,healed:0,attackRelease:0,walkDistance:0,motionBlend:0,travelFacing:1,angle:0};this.placeSummon(unit);s.summons.push(unit);this.effect('spawn',unit.x,unit.y,{radius:45,color:'#7ceade',life:.5});}
  this.notice(spec.name+' actief · T geeft een doel aan','#a1e7de');this.emit('summon');return true;
 },
 selectCompanion(id){const p=this.state.player;if(this.challengeBuildLocked()||!COMPANIONS[id]||!p.skills.includes('summon')||!summonAvailable(p)||p.level<10&&id!=='scout'||id==='mender'&&!p.menderUnlocked)return false;p.companionProfile=id;return true;},
 commandCompanions(point){const s=this.state,p=s.player;if(this.inCamp()||!(s.summons?.length)||(p.commandCd||0)>0)return false;const target=s.world.enemies.filter(e=>!e.dead&&!e.hidden&&dist(e,point)<110).sort((a,b)=>dist(a,point)-dist(b,point))[0];p.summonTarget=target?.id||null;p.commandCd=.6;if(target)this.notice('Je dieren richten op '+ENEMIES[target.type].name,'#a1e7de');return Boolean(target);},
 updateCompanions(dt){const s=this.state,p=s.player;p.commandCd=Math.max(0,(p.commandCd||0)-dt);s.summons||=[];if(this.inCamp()){s.summons=[];return;}
  for(const u of s.summons){if(!u.persistent)u.life-=dt;u.cd-=dt;u.attackRelease=Math.max(0,u.attackRelease-dt);if(u.hp<=0||u.life<=0)continue;const spec=u.spirit?{...COMPANIONS[u.profile],damage:22}:COMPANIONS[u.profile],enemies=s.world.enemies.filter(e=>!e.dead&&!e.hidden),assigned=enemies.find(e=>e.id===p.summonTarget),target=assigned||enemies.sort((a,b)=>dist(a,u)-dist(b,u))[0];
   const desired=target&&dist(target,p)<650?{x:target.x+(u.profile==='guardian'?-65:-180),y:target.y+60}:{x:p.x+(u.id%2?65:-65),y:p.y+45},old={x:u.x,y:u.y};this.moveCompanionToward(u,desired,dt);
   const moved=Math.hypot(u.x-old.x,(u.y-old.y)/.78);u.walkDistance=(u.walkDistance||0)+moved;u.motionBlend=(u.motionBlend||0)+(Number(moved>dt*3)-(u.motionBlend||0))*(1-Math.exp(-dt*12));if(Math.abs(u.x-old.x)>dt*12)u.travelFacing=u.x<old.x?-1:1;if(target)u.angle=Math.atan2((target.y-u.y)*1.15,target.x-u.x);
   for(const bolt of s.projectiles){if(bolt.team!=='enemy'||bolt.life<=0||['enemy-carrier','enemy-lob'].includes(bolt.type))continue;if(dist({x:bolt.x,y:bolt.y+20},u)<(u.profile==='guardian'?45:23)+bolt.radius){this.companionDamage(u,bolt.damage);bolt.life=0;this.effect('impact',u.x,u.y-20,{color:'#82e4db',radius:25,life:.25});}}
   for(const e of enemies)if(dist(e,u)<e.radius+24&&!e.stun)this.companionDamage(u,dt*ENEMIES[e.type].damage*(e.damageMultiplier||1)*.42);
   if(u.profile==='guardian')for(const e of enemies)if(!ENEMIES[e.type].boss&&dist(e,u)<110)e.slow=Math.max(e.slow||0,.3);
   if(u.hp<=0)continue;
   if(u.cd<=0){u.cd=spec.interval;u.attackRelease=.3;if(u.profile==='mender'){if(dist(u,p)<260&&u.healed<24+(this.stats().menderCap||0)+(u.training?.potency||0)*4&&p.hp<this.stats().maxHp){const heal=Math.min(this.stats().menderCap?4:3,24+(this.stats().menderCap||0)+(u.training?.potency||0)*4-u.healed,this.stats().maxHp-p.hp);u.healed+=heal;p.hp+=heal;this.effect('chain',u.x,u.y-25,{end:{x:p.x,y:p.y-25},color:'#a5e7b5',life:.25});}}
    else if(u.profile==='guardian'&&target&&dist(u,target)<120){this.hitEnemy(target,spec.damage*(1+Math.min(.65,this.stats().power))*(1+(this.stats().minionDamage||0)+(u.training?.potency||0)*.12)*(this.hasUnique('command')?1.22:1),'physical',true);this.effect('slash',u.x,u.y-10,{dir:{x:Math.cos(u.angle),y:Math.sin(u.angle)},radius:55,color:'#dcdf93',life:.25});}
    else if(u.profile!=='guardian'&&target&&dist(u,target)<480){const n=Math.hypot(target.x-u.x,(target.y-u.y)*1.15)||1,dx=(target.x-u.x)/n,dy=(target.y-u.y)*1.15/n;s.projectiles.push({id:++this.idCounter,team:'player',group:++this.idCounter,companion:true,type:spec.element,x:u.x,y:u.y-24,vx:dx*520,vy:dy*520/1.15,damage:spec.damage*(1+Math.min(.65,this.stats().power))*(1+(this.stats().minionDamage||0)+(u.training?.potency||0)*.12)*(this.hasUnique('command')?1.22:1),radius:6,life:1.2,age:0,trail:[],hitIds:[]});}}
  }s.summons=s.summons.filter(u=>u.hp>0&&u.life>0);
 }
};
export function companionMenu(p){const available=summonAvailable(p),learned=p.skills.includes('summon')&&available,early=p.level<10,unlock=summonUnlockLevel(p);return `<section class="animal-companions"><h3>Dierenverbond <small>${learned?early?'EERSTE GETIJVOS · ROEDEL OP NIVEAU 10':'VOLLEDIG VERBOND':`VANAF NIVEAU ${unlock} · 1 PUNT`}</small></h3><p class="menu-intro">${learned?early?'Je eerste getijvos helpt met waterlicht. Vanaf niveau 10 krijgt je verbond meer dieren en rollen. T: wijs een vijand onder je cursor aan.':'Roep je dieren op met de toets van Dierenverbond. T: wijs een vijand onder je cursor aan. Kies hieronder het dier voor je volgende oproep. Gevallen dieren roep je zelf opnieuw op. Een nieuwe oproep vervangt de groep.':available?`Leer Dierenverbond voor één vaardigheidspunt${early?' om één eenvoudige getijvos op te roepen':''}. Plaats de spreuk vervolgens op een nummer of je rechtermuisknop.`:`Vanaf niveau ${unlock} kun je ${unlock===4?'één eenvoudige getijvos':'het volledige Dierenverbond'} leren. ${unlock===4?'Je volledige dierenverbond opent op niveau 10.':'Alleen de Natuurhoeder krijgt al op niveau 4 een eerste getijvos.'}`}</p>${!learned?`<button data-learn-summon ${available&&p.skillPoints>0&&!p.skills.includes('summon')?'':'disabled'}>${available?'Leer Dierenverbond · 1 punt':`Beschikbaar op niveau ${unlock}`}</button>`:''}<div class="companion-options">${Object.entries(COMPANIONS).map(([id,c])=>`<button data-companion="${id}" ${!learned||early&&id!=='scout'||id==='mender'&&!p.menderUnlocked?'disabled':''} aria-pressed="${learned&&(early?'scout':p.companionProfile||'scout')===id}"><img src="assets/items/${c.art}.webp" alt=""><strong>${id==='scout'&&early&&unlock===4?'Eerste getijvos':c.name}</strong><p>${id==='scout'&&early&&unlock===4?'Eén kwetsbare geestvos schiet waterlicht. Blijft tot hij valt · 26 mana.':c.text}</p><small>${early&&(id!=='scout'||unlock!==4)?'VOLLEDIG VERBOND · NIVEAU 10':id==='mender'&&!p.menderUnlocked?'ILYA’S OPDRACHT · VRIJHAVEN':'TOT HIJ VALT · '+c.hp+' basisleven'}</small></button>`).join('')}</div></section>`;}
