import {ENEMIES} from './data.js?v=910';
import {launchEnemyLob} from './enemy-combat.js?v=910';
const dist=(a,b)=>Math.hypot(a.x-b.x,(a.y-b.y)*1.15);
const unit=(x,y)=>{const n=Math.hypot(x,y)||1;return {x:x/n,y:y/n};};
export const V6_ENEMIES=['bulwark','plaguewright','hunter','repairer','tideleviathan','solararchitect','pressurediver','rimedrone','furnacegunner','deepwarden','towerwarden'];
export const V6EnemyRules={
 planV6Attack(e){if(!V6_ENEMIES.includes(e.type))return false;const p=this.enemyTarget(e),dir=unit(p.x-e.x,(p.y-e.y)*1.15);e.attacks=(e.attacks||0)+1;const sets={pressurediver:['harpoonVolley','snapShot','shieldFan'],rimedrone:['snapShot','huntShots','huntDash'],furnacegunner:['firePatches','snapShot','shieldFan'],deepwarden:['floodLanes','tidalRing','harpoonVolley'],towerwarden:['firePatches','sunWheel','solarBarriers'],bulwark:['shieldBash','shieldFan'],plaguewright:['plagueLob','toxicFan'],hunter:['huntDash','huntShots'],repairer:['repairPulse','huntShots'],tideleviathan:['floodLanes','icePatches','harpoonVolley'],solararchitect:['firePatches','sunWheel','solarBarriers']},mode=sets[e.type][(e.attacks-1)%sets[e.type].length],quick=mode==='snapShot'||mode==='huntShots'&&['hunter','rimedrone'].includes(e.type),time=quick?(e.type==='rimedrone'?.3:.42):mode==='huntDash'?.85:mode==='repairPulse'?.9:1.3;
  e.windup={mode,dir,target:{x:p.x,y:p.y},timer:time,total:time,quick};if(mode==='plagueLob')e.windup.targets=[{x:p.x,y:p.y},{x:p.x+100*dir.y,y:p.y-85*dir.x}];if(mode==='floodLanes')e.windup.lanes=[p.y-100,p.y+100].map(y=>Math.max(400,Math.min(920,y)));if(mode==='mirrorCross')e.windup.targets=[{x:p.x-130,y:p.y},{x:p.x+130,y:p.y}];this.planTerrainAttack(e);this.emit('windup',{type:e.type});return true;
 },
 executeV6Attack(e){if(!V6_ENEMIES.includes(e.type)||!e.windup)return false;if(this.inCamp())return true;const s=this.state,w=e.windup,base=ENEMIES[e.type],damage=base.damage*(e.damageMultiplier||1),add=t=>s.world.threats.push({id:++this.idCounter,age:0,source:e.id,damage,color:base.color,...t}),fan=(n,spread,speed=430)=>{for(let i=0;i<n;i++){const a=Math.atan2(w.dir.y,w.dir.x)+(i-(n-1)/2)*spread;s.projectiles.push({id:++this.idCounter,team:'enemy',type:e.type,x:e.x,y:e.y-30,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed/1.15,damage,radius:8,age:0,life:2.5,trail:[],color:base.color,element:base.element,damageType:base.element==='water'?'water':base.element==='solar'?'fire':base.element==='frost'?'water':undefined,venom:w.mode==='toxicFan'});}};
  this.executeTerrainAttack(e,damage);
  if(['shieldBash','huntDash'].includes(w.mode)){e.rush={dir:w.dir,life:w.mode==='huntDash'?.4:.22,damage,hit:false};this.effect('slash',e.x,e.y,{dir:w.dir,color:base.color,radius:110,life:.3});}
  if(w.mode==='snapShot'){fan(1,0,620);s.projectiles.at(-1).damage*=.78;}if(w.mode==='shieldFan')fan(3,.32,320);if(w.mode==='huntShots')fan(2,.12,610);if(w.mode==='toxicFan')fan(3,.3,320);if(w.mode==='harpoonVolley')fan(e.phase===2?5:3,.18,570);
  if(w.mode==='plagueLob')for(const [i,p]of w.targets.entries())launchEnemyLob(this,e,p,{duration:.55+i*.15,damage,radius:65,poison:true,element:'toxin'});
  if(w.mode==='repairPulse'){const target=s.world.enemies.filter(n=>n!==e&&!n.dead&&!ENEMIES[n.type].boss&&dist(n,e)<340&&n.hp<n.maxHp&&(n.repairs||0)<3).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(target){target.hp=Math.min(target.maxHp,target.hp+target.maxHp*.1);target.repairs=(target.repairs||0)+1;this.effect('chain',e.x,e.y-45,{end:{x:target.x,y:target.y-35},color:'#edb76d',life:.5});}else fan(2,.18,350);}
  if(w.mode==='floodLanes')for(const y of w.lanes)add({type:'v6lane',x:960,y,r:52,length:1200,arm:.55,life:3.6,tick:0,element:base.element||'toxin',venom:!base.element});
  if(w.mode==='tidalRing')add({type:'ring',x:e.x,y:e.y,r:55,width:24,speed:e.phase===2?330:260,life:1.8,hit:false,element:base.element||'toxin',venom:!base.element});
  if(w.mode==='mirrorCross')for(const p of w.targets)add({type:'v6lane',x:p.x,y:p.y,vertical:true,r:45,length:680,arm:.6,life:1.8,tick:0,element:'solar'});
  if(w.mode==='sunWheel')for(let i=0;i<(e.phase===2?12:8);i++){const a=e.angle+i*Math.PI*2/(e.phase===2?12:8);s.projectiles.push({id:++this.idCounter,team:'enemy',type:'sunWheel',x:e.x,y:e.y-35,vx:Math.cos(a)*285,vy:Math.sin(a)*285/1.15,damage,radius:10,age:0,life:2.8,trail:[],color:base.color,element:base.element,damageType:base.element==='solar'?'fire':undefined});}
  if(w.mode==='solarSweep')add({type:'sweep',x:e.x,y:e.y,angle:Math.atan2(w.dir.y,w.dir.x)-.55,length:530,life:1.2,tick:0,element:'solar'});
  this.emit('enemyattack',{enemy:e.type,mode:w.mode});return true;
 },
 updateV6Enemy(e){if(!V6_ENEMIES.includes(e.type))return;const p=this.state.player;if(ENEMIES[e.type].boss&&e.hp<e.maxHp*.5&&e.phase<2){e.phase=2;e.cd=.5;e.cooldownMultiplier*=.83;this.effect('nova',e.x,e.y,{radius:130,color:ENEMIES[e.type].color,life:.6});this.notice(ENEMIES[e.type].name+' · tweede fase');this.emit('bossphase',{enemy:e.type,phase:2});}if(e.type==='bulwark'&&!e.windup&&e.wet<=0)e.protectionTarget=this.state.world.enemies.filter(n=>n!==e&&!n.dead&&dist(n,e)<140).sort((a,b)=>dist(a,p)-dist(b,p))[0]?.id;else e.protectionTarget=null;},
 protectedDamage(e,damage){if(e.type==='bulwark'&&!e.windup&&e.wet<=0){const p=this.state.player,n=unit(p.x-e.x,(p.y-e.y)*1.15);if(n.x*Math.cos(e.angle)+n.y*Math.sin(e.angle)>.35)damage*=.55;}if(this.state.world.enemies.some(n=>!n.dead&&n.protectionTarget===e.id&&!n.windup&&n.wet<=0))damage*=.72;return damage;},
 updateV6Threats(dt){const s=this.state,p=s.player;for(const t of s.world.threats){if(t.type!=='v6lane'||t.age<t.arm)continue;t.tick-=dt;if(t.tick<=0){t.tick=.75;const across=t.vertical?Math.abs(p.x-t.x):Math.abs(p.y-t.y)*1.15,along=t.vertical?Math.abs(p.y-t.y)*1.15:Math.abs(p.x-t.x);if(across<t.r&&along<t.length/2){this.hurtPlayer(t.damage,t.venom?'venomHit':t.element);if(t.element==='water')p.wet=Math.max(p.wet,1.5);}}}},
 interceptCompanion(b,old){if(b.team!=='enemy')return false;for(const u of this.state.summons||[]){if(u.hp<=0||u.life<=0)continue;const a={x:old.x,y:old.y+20},end={x:b.x,y:b.y+20},dx=end.x-a.x,dy=end.y-a.y,len=dx*dx+dy*dy,t=Math.max(0,Math.min(1,len?((u.x-a.x)*dx+(u.y-a.y)*dy)/len:0));if(Math.hypot(a.x+t*dx-u.x,(a.y+t*dy-u.y)*1.15)<(u.profile==='guardian'?42:20)+(b.radius||0)){this.companionDamage(u,b.damage);b.life=0;this.effect('impact',u.x,u.y-20,{radius:30,color:'#83e2d8',life:.25});return true;}}return false;}
};
