import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Engine,canStand,findPath,copy} from '../src/engine.js';
import {makeItem} from '../src/loot.js';
import {SPELLS,AREA_BY_ID} from '../src/data.js';
import {SPECIALIZATIONS,specializationStats} from '../src/specializations.js';
import {spellProfile} from '../src/spell-variants.js';
import {ADVENTURES,ADVENTURE_NPCS} from '../src/adventures.js';
import {INVESTMENTS,SPELL_OFFERS} from '../src/markets.js';
import {enterTargetSection} from './walk-section.js';
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS '+name);};
function arena(){const g=new Engine('tide',734);g.enterArea('ring');g.state.world.enemies=[];g.state.world.hazards=[];Object.assign(g.state.player,{x:850,y:640,level:12,invincible:0,mana:110});g.state.player.stats.crit=-.07;return g;}
function dummy(g,x=1100,y=640){const e=g.makeEnemy('turret',x,y,false,true);e.hp=e.maxHp=10000;e.cd=99;g.state.world.enemies.push(e);return e;}
test('Specialisatie heeft drie echte keuzerijen, geen extra aanvalsknop en geen gratis respec in combat',()=>{for(const [id,s]of Object.entries(SPECIALIZATIONS)){const g=arena(),p=g.state.player;p.level=4;assert(!g.chooseSpecialization(id));p.level=5;const points=p.skillPoints;assert(g.chooseSpecialization(id));assert(!g.chooseSpecialization(id));assert(g.chooseTalent(0,s.tiers[0][0].id));assert(!g.chooseTalent(0,s.tiers[0][1].id));assert(!g.chooseTalent(1,s.tiers[1][0].id));p.level=8;assert(g.chooseTalent(1,s.tiers[1][0].id));p.level=11;assert(g.chooseTalent(2,s.tiers[2][0].id));assert.equal(p.skillPoints,points);assert(Object.keys(specializationStats(p)).length>0);p.scrap=300;p.hp=g.stats().maxHp*.4;p.mana=g.stats().maxMana*.3;assert(!g.resetSpecialization());g.enterArea('canal');const hp=p.hp/g.stats().maxHp,mana=p.mana/g.stats().maxMana;assert(g.resetSpecialization());assert.equal(p.scrap,0);assert(Math.abs(p.hp/g.stats().maxHp-hp)<1e-8);assert(Math.abs(p.mana/g.stats().maxMana-mana)<1e-8);assert.equal(p.specialization,null);}});
test('Talenten veranderen lanceringskosten, gebiedsbereik en constructie-aantal zonder recast of resource-reset',()=>{let g=arena(),p=g.state.player;g.chooseSpecialization('elementalist');g.chooseTalent(1,'widefields');assert.equal(spellProfile(p,'cryo').radius,SPELLS.cryo.radius*1.15);g=arena();p=g.state.player;g.chooseSpecialization('hunter');g.chooseTalent(0,'cartridges');assert.equal(spellProfile(p,'prism').cost,16);g=arena();p=g.state.player;g.chooseSpecialization('builder');g.chooseTalent(0,'overclock');g.chooseTalent(1,'assembly');g.chooseTalent(2,'squad');p.skills.push('summon');const mana=p.mana;assert(g.cast('summon'));assert.equal(p.mana,mana-34);assert.equal(p.spellCd.summon,15);assert.equal(g.state.summons.length,3);assert(g.state.summons[0].persistent);assert(g.state.summons[0].maxHp>34);dummy(g,1050);g.updateCompanions(.6);const bolt=g.state.projectiles.find(b=>b.companion);assert.equal(bolt.damage,10);});
test('Prismaboog is efficiënt maar vereist een eerste gerichte treffer en raakt verschillende doelen en eindigt met een explosie',()=>{const g=arena(),p=g.state.player;p.skills.push('prism');p.x=700;const enemies=[900,1070,1240,1400].map(x=>dummy(g,x));g.aimAt(1500,640);assert(g.cast('prism'));assert.equal(p.spellCd.prism,1);assert.equal(p.mana,92);assert(enemies.every(e=>e.hp===10000));for(let i=0;i<100;i++)g.updateProjectiles(.016);const loss=enemies.map(e=>10000-e.hp);assert(Math.abs(loss[0]-100)<1e-6);assert(Math.abs(loss[3]-100*.92**3*1.5)<1e-6);assert(loss.reduce((a,b)=>a+b,0)/18>12);g.state.projectiles=[];p.spellCd.prism=0;g.aimAt(700,200);g.cast('prism');for(let i=0;i<100;i++)g.updateProjectiles(.016);assert.deepEqual(enemies.map(e=>10000-e.hp),loss);});
test('Donderlans doorboort vier doelen, gebruikt stormcombinaties en Winterkroon geeft vier aparte schadepulsen',()=>{let g=arena(),p=g.state.player;p.skills.push('volt');p.x=700;const enemies=[900,1050,1200,1350,1500].map(x=>dummy(g,x));enemies[0].wet=3;g.aimAt(1500,640);assert(g.cast('volt'));for(let i=0;i<100;i++)g.updateProjectiles(.016);assert(enemies.slice(0,4).every(e=>e.hp<10000));assert.equal(enemies[4].hp,10000);assert(10000-enemies[0].hp>90);g=arena();p=g.state.player;p.skills.push('cryo');const e=dummy(g,1100);g.aimAt(e.x,e.y);assert(g.cast('cryo'));g.updateFields(.29);assert.equal(e.hp,10000);g.updateFields(.02);assert.equal(e.hp,9820);g.updateFields(.5);assert.equal(e.hp,9775);g.updateFields(.6);assert.equal(e.hp,9730);g.updateFields(.6);assert.equal(e.hp,9685);assert(e.slow>0);});
test('Drie betaalde spreuken hebben regio-, level- en geldgrenzen; kopen verandert je bindings niet',()=>{for(const [id,o]of Object.entries(SPELL_OFFERS)){const g=new Engine();g.state.completed=true;g.enterArea(['canal','highway','forest','skybridge'][o.minZone]);const p=g.state.player,m=g.hubMerchants().find(m=>m.id==='smith');Object.assign(p,{x:m.x,y:m.y,level:o.level,scrap:o.price});g.interact();const slots=copy(p.hotbar),right=p.rightAbility;assert(g.buySpell(id));assert.equal(p.scrap,0);assert.deepEqual(p.hotbar,slots);assert.equal(p.rightAbility,right);assert(!g.buySpell(id));assert(!g.purchaseUpgrade({skill:true,id}));assert(Engine.restore(g.serialize()).state.player.skills.includes(id));}});
test('Spaarstukken hebben vaste stats per regio, onderscheiden leveranciers en verdwijnen blijvend na aankoop',()=>{let previous=0;for(let zone=0;zone<4;zone++){const g=new Engine();g.state.completed=true;g.enterArea(['canal','highway','forest','skybridge'][zone]);const p=g.state.player,items=g.state.world.shop.stock.filter(i=>i.investment);assert.equal(items.length,zone<2?7:8);assert.equal(new Set(INVESTMENTS[zone].map(i=>i.slot)).size,6);const focus=items.find(i=>i.slot==='weapon'&&i.rarity==='epic');assert(focus.stats.power>previous);previous=focus.stats.power;const m=g.hubMerchants().find(m=>m.id==='smith');Object.assign(p,{x:m.x,y:m.y,scrap:focus.price,level:14});g.interact();assert(g.serviceStock().some(i=>i.uid===focus.uid));const worn=p.equipment.weapon.uid;assert(g.buyItem(focus.uid));assert.equal(p.equipment.weapon.uid,worn);assert(g.equipItem(focus.uid));assert.equal(p.equipment.weapon.uid,focus.uid);const r=Engine.restore(g.serialize());r.retry();assert(!r.state.world.shop.stock.some(i=>i.investment===focus.investment));}});
test('Vier nevenroutes hebben bereikbare punten, betaalde eindbeloning één keer en een afgesloten terugpoort',()=>{for(const [id,spec]of Object.entries(ADVENTURES)){const g=new Engine();g.state.completed=true;g.enterArea(spec.hub);const p=g.state.player;p.hp=62;p.mana=27;p.potions=1;assert(g.startAdventure(id));assert.equal(p.hp,62);assert.equal(p.mana,27);assert.equal(p.potions,1);assert(!g.portalReady());assert.equal(g.state.world.enemies.length,7);for(const o of g.state.world.objectives){assert(canStand(o.x,o.y,35,id));assert(findPath(p,o,id,24).length);Object.assign(p,{x:o.x,y:o.y});assert(!g.collectAdventureObjective(o.id));for(const e of g.state.world.enemies.filter(e=>e.objectiveId===o.id))g.killEnemy(e);assert(g.collectAdventureObjective(o.id));assert(!g.collectAdventureObjective(o.id));}const cash=p.scrap,xp=p.xp;assert(g.updateAdventure());assert.equal(p.scrap,cash+spec.reward);assert.equal(p.xp,xp+spec.xp);assert.equal(g.state.world.loot.length,1);assert(g.portalReady());assert.equal(g.state.world.portals[0].to,spec.hub);assert(!g.updateAdventure());g.enterArea(spec.hub);assert(g.startAdventure(id));assert.equal(g.state.world.adventure.claimed.length,0);assert.equal(g.state.world.enemies.filter(e=>!e.dead).length,7);}});
test('Nevenroute-NPCs blijven op ruim bereikbare wandelpaden; routes vereisen hun verhaalmijlpaal',()=>{for(const [area,n]of Object.entries(ADVENTURE_NPCS)){const g=new Engine();g.state.completed=true;g.enterArea(area);if(area==='canal')g.state.world.gardenOpen=true;enterTargetSection(g,n);assert(canStand(n.x,n.y,35,area));assert(g.findWalkingPath(g.state.player,n,24).length);Object.assign(g.state.player,{x:n.x,y:n.y});assert.equal(g.interaction().type,'quest');assert.equal(g.interaction().entity.id,'routes');}const g=new Engine();assert(!g.startAdventure('adventure-metro'));g.state.storyPassed=['delta'];assert(g.startAdventure('adventure-metro'));});
test('Baasgrond is aangekondigd, eindig en pijnlijk; weerstand en uit de cirkel stappen verminderen schade',()=>{for(const mode of ['firePatches','icePatches']){const g=arena(),p=g.state.player,e=dummy(g);e.windup={mode,dir:{x:1,y:0},target:{x:p.x,y:p.y}};g.planTerrainAttack(e);g.executeTerrainAttack(e,30);const t=g.state.world.threats[0];assert.equal(t.age,0);const hp=p.hp;g.updateBossTerrain(.01);assert.equal(p.hp,hp);t.age=1;g.updateBossTerrain(.01);assert.equal(p.hp,hp-24);p.invincible=0;p.stats[mode==='firePatches'?'fireResist':'waterResist']=.5;t.tick=0;g.updateBossTerrain(.01);assert.equal(p.hp,hp-36);p.x+=150;p.invincible=0;const before=p.hp;t.tick=0;g.updateBossTerrain(.01);assert.equal(p.hp,before);assert(t.life<=6);}});
test('Tijdelijke blokkades houden lopen tegen maar sluiten een speler die tijdens opbouw binnenloopt niet op',()=>{const g=arena(),p=g.state.player,t={type:'bossBarrier',x:950,y:640,r:36,age:0,arm:.8,life:5};g.state.world.threats=[t];assert(!g.blockedByBossTerrain(950,640));t.age=1;assert(g.blockedByBossTerrain(950,640));p.x=885;g.moveEntity(p,20,0);assert.equal(p.x,885);p.x=950;g.moveEntity(p,15,0);assert.equal(p.x,965);t.life=0;assert(!g.blockedByBossTerrain(950,640));});
test('Nieuwe assets bestaan, vier vijandrollen hebben vier loop- en twee aanvalshoudingen',()=>{const frames=JSON.parse(fs.readFileSync(new URL('../assets/expedition/enemy-walk-v7.json',import.meta.url)));for(const [type,spec]of Object.entries(frames)){assert.equal(spec.frames.length,6);assert(spec.scaleDenominator>0);}for(const id of Object.keys(ADVENTURES))assert(fs.existsSync(new URL('../assets/painted/'+AREA_BY_ID[id].file,import.meta.url)));for(const id of ['prism','volt','cryo'])assert(fs.existsSync(new URL('../assets/items/skill-'+id+'.webp',import.meta.url)));assert(fs.existsSync(new URL('../assets/painted/hero-equipment-v7.webp',import.meta.url)));});
test('Tweede relikwieslot telt stats op, weigert verkeerde types en geeft geen leeg item of gratis herstel',()=>{const g=new Engine(),p=g.state.player;assert.equal(Object.keys(p.equipment).length,8);assert(p.equipment.relic2.empty);const item=makeItem({rng:g.rng,slot:'relic',level:1,rarity:'rare',uid:++g.idCounter});p.inventory.push(item);const first=p.equipment.relic.uid,before=g.stats();p.hp=before.maxHp*.4;p.mana=before.maxMana*.3;assert(!g.equipItem(item.uid,'boots'));assert.equal(p.inventory.length,1);assert(g.equipItem(item.uid,'relic2'));assert.equal(p.equipment.relic.uid,first);assert.equal(p.inventory.length,0);assert.equal(g.stats().mana,before.mana+(item.stats.mana||0));assert(Math.abs(p.hp/g.stats().maxHp-.4)<1e-8);assert(Math.abs(p.mana/g.stats().maxMana-.3)<1e-8);const replacement=makeItem({rng:g.rng,slot:'relic',level:1,rarity:'common',uid:++g.idCounter});p.inventory.push(replacement);assert(g.equipItem(replacement.uid,'relic2'));assert.equal(p.inventory.length,1);assert.equal(p.inventory[0].uid,item.uid);const m=g.hubMerchants().find(m=>m.id==='workshop');Object.assign(p,{x:m.x,y:m.y,scrap:300});const regen=g.stats().regen;assert(g.reinforce('relic2'));assert.equal(g.stats().regen,regen+1.4);assert(g.reinforce('relic2','poisonResist'));assert.equal(p.equipment.relic2.stats.poisonResist,.08);g.checkpoint();const r=Engine.restore(g.serialize());assert.equal(r.state.player.equipment.relic2.uid,replacement.uid);r.retry();assert.equal(r.state.player.equipment.relic2.enhance,2);const empty=new Engine();assert(!empty.reinforce('relic2'));const old=JSON.parse(empty.serialize());delete old.state.player.equipment.relic2;delete old.state.checkpoint.player.equipment.relic2;const migrated=Engine.restore(JSON.stringify(old));assert(migrated.state.player.equipment.relic2.empty);assert(migrated.state.checkpoint.player.equipment.relic2.empty);});
test('Levenshoeder levert maximaal 36 herstel en blijft daarna zonder extra genezing',()=>{const g=arena(),p=g.state.player;g.chooseSpecialization('builder');g.chooseTalent(2,'support');p.skills.push('summon');p.menderUnlocked=true;p.companionProfile='mender';p.hp=10;assert(g.cast('summon'));for(let i=0;i<190;i++)g.updateCompanions(.1);assert.equal(p.hp,46);assert(g.state.summons.length===1);for(let i=0;i<200;i++)g.updateCompanions(.1);assert.equal(p.hp,46);});
console.log('\n'+n+' v7-groepen geslaagd.');
